- lua/modules/completion/config.lua
- lua/modules/completion/lsp.lua
- lua/modules/completion/plugins.lua
- lua/modules/editor/config.lua
- lua/modules/editor/plugins.lua
- lua/modules/tools/config.lua
- lua/modules/tools/plugins.lua
These two plugins are written in Lua and have good compatibility with CMP and LSP. They provide more accurate completion and highlighting, and do not affect the use experience when large files are used
> Use cmp-cmdline and illuminate to improve the use experience

- lua/modules/editor/config.lua
- lua/modules/editor/plugins.lua
> Revert "feat: Add brglng/vim-im-select to change input method automatically."

- lua/modules/completion/formatting.lua
1. 将 format 的 vim.cmd 替换为了 `nvim_create_user_command`，更直观些 代码跳转也更友好。
2. 增加了一个控制单独 lsp format 的开关，efm 在写 markdown 时 format 太慢了，没有必要每次保存都格式化下，当前想到的最好方法就是单独禁止了，如果有更好的方式请告诉我~
> chang vim.cmd and add format control

- lua/modules/editor/plugins.lua
作者已将最新分支设置为了v2，详见 [hop.nvim](https://github.com/phaazon/hop.nvim) 的主页
> chore(hop.nvim): Updated version to latest one (v2)

- lua/modules/completion/config.lua
> fix eslint error

- lua/modules/ui/config.lua
Sorry I didn't consider `BufferLineWarning`s. Here's the quick fix <3
> fix(catppuccin): Integration with bufferline warnings.

- lua/modules/completion/plugins.lua
RT. See https://github.com/glepnir/lspsaga.nvim/commit/b59ff0d1752f7e9ef93363b71a2cd9b8f2011fec
> perf: Remove FixCursorHold due to usage of CurosrMoved with timer.

- lua/modules/editor/plugins.lua
[issue under packer.nvim](https://github.com/wbthomason/packer.nvim/issues/1039)
> this plugin causes lazy load problem

- lua/modules/ui/config.lua
- Special configs for TS-Rainbow were removed.
- > Ref: https://github.com/catppuccin/nvim/commit/f1ad3cf9fb5de3e2e39807b01b26ca02d5371e1e
- Enabled integration with fidget. I've gently modified its highlights so that they could better fit in daily display/usage.
> chore(catppuccin): Update options from upstream.

- lua/modules/tools/plugins.lua
The account [tami5](https://github.com/tami5) has been migrated [kkharji](https://github.com/kkharji). We need to update all relevant repo _(s)_. 👍
> chore(sqlite): Update repo owner.

- lua/modules/editor/config.lua
- lua/modules/ui/config.lua
> Ref: https://github.com/catppuccin/nvim/commit/b4526a7e7ef39b9cc009aedeaf06a8d0706aaed1
> chore(catppuccin & illuminate): Use default integration.

- lua/modules/editor/config.lua
Part of https://github.com/ayamir/nvimdots/issues/242. _(for dapui widgets)_
> feat(dapui): Enable clickable control widgets.

- lua/modules/ui/config.lua
> Ref: https://github.com/catppuccin/nvim/commit/a111e8075101c0ac8be79f293e8c5181efa06402
> chore(bufferline & catppuccin): Update integration. [main]

- lua/modules/ui/config.lua
> Ref: https://github.com/catppuccin/nvim/commit/a111e8075101c0ac8be79f293e8c5181efa06402
> chore(bufferline & catppuccin): Update integration. [0.7]

- lua/core/init.lua
- lua/core/pack.lua
- lua/modules/tools/config.lua
- lua/modules/ui/config.lua
Part of #242, detailed description at #250. I've also modified several prompts and error assertion logic.
> Once merged, this would mark #250 as completed and resolve #250.
> style: Migrate vimscript to lua code

- lua/modules/completion/config.lua
- lua/modules/ui/config.lua
Attempting to address https://github.com/ayamir/nvimdots/issues/242#issuecomment-1268445852.
> chore(v0.8): Cleanup.

- lua/core/init.lua
- lua/modules/tools/config.lua
- lua/modules/tools/plugins.lua
> cleanup(core): Remove filetype.lua settings

- lua/modules/ui/config.lua
> chore(catppuccin): Update compile fn. [0.7]

- lua/core/init.lua
- lua/keymap/config.lua
- lua/modules/completion/config.lua
- lua/modules/completion/lsp.lua
- lua/modules/editor/config.lua
- lua/modules/lang/config.lua
- lua/modules/tools/config.lua
- lua/modules/ui/config.lua
> Ref: https://github.com/catppuccin/nvim/pull/289
> chore(catppuccin): Update compile fn.

- lua/core/init.lua
Update `disable_distribution_plugins` and cleanup nonsense options.
> Update `disable_distribution_plugins`, fix #266

- lua/core/options.lua
Part of #251. Added option: `mousescroll`.
> feat(options): Add precise mouse scroll support.

- install/install.sh
Part of https://github.com/ayamir/nvimdots/pull/273#issuecomment-1276057425.
> feat(script): Support HTTPS.

- lua/modules/ui/icons.lua
https://github.com/ayamir/nvimdots/pull/287#discussion_r996375605 and https://github.com/ayamir/nvimdots/pull/287#discussion_r996374839
> chore(icons-utils): Cleanup.

- lua/modules/ui/config.lua
We still need `vim.g.catppuccin_flavour` to set the palette correctly
> fix(catppuccin): Set global palette properly.

- install/install.sh
\* Emphasize that users must follow the wiki to complete installation.
> chore(script): Emphasize the need to read wiki.

- lua/modules/completion/lsp.lua
- lua/modules/editor/config.lua
I do some simple tests, I think it won't cause issues. But still, please examine it.
refer to #313
> chore(nvim-treesitter): update get_parser_configs with ssh preference

- lua/modules/editor/config.lua
> chore(smartyank): enable osc52 in remote tmux

- lua/modules/ui/config.lua
See: https://github.com/nvim-tree/nvim-tree.lua/commit/99d713644d44b573d076812ee5bfcaa5290aaa25.
> chore(nvim-tree): root_folder_modifier -> root_folder_label

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/lsp_issue_report.yml
> chore(issue-template): Query download preferences

- lua/modules/completion/formatting.lua
> fix typo "worksapces"

- lua/modules/ui/config.lua
- lua/modules/ui/plugins.lua
> feat: New plugin - zbirenbaum/neodim

- lua/modules/tools/config.lua
- lua/modules/tools/plugins.lua
Frecency sorting was introduce to legendary.nvim few days a ago. I thought it's nice to have it. But if you don't think it's a good idea, fell free to close the PR!
> chore(legendary): add frecency sorting

- lua/modules/completion/config.lua
- lua/modules/completion/plugins.lua
> fix: fix copilot issue when using dap

- lua/modules/completion/plugins.lua
- lua/modules/editor/plugins.lua
and some minor improvements for loading order.
fix part of the issue from #395
> Change loading order to avoid `cmp not found` when opening new file.

- lua/modules/ui/config.lua
> Ref: https://github.com/ayamir/nvimdots/pull/402#issuecomment-1370747565
End result:
> chore(lualine): Update layout

- lua/modules/utils/init.lua
This commit checks some corner cases so that utilities can return correctly in any case.
> fix(utils): Check parameters' validity

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/lsp_issue_report.yml
Inspired by: https://github.com/ayamir/nvimdots/issues/406#issuecomment-1371962324.
This addition produces the following effect:
**Version confirmation**
The local configuration is up-to-date in the current branch and this issue _persists_.
> pref(issue-template): Confirm latest commit

- lua/core/options.lua
> fix(dap): Allow jumping between files

- install/install.ps1
- install/install.sh
- lua/modules/completion/config.lua
- lua/modules/lang/plugins.lua
Resolves #448. @ayamir @CharlesChiuGit Can you test this script on Windows? It executes correctly on macOS running `pwsh core`.
Command:
```pwsh
Invoke-WebRequest "https://raw.githubusercontent.com/Jint-lzxy/nvimdots/feat/windows-installer/install/install.ps1" -UseBasicParsing | Invoke-Expression
```
> feat(script): Complete installation script on Windows.

- README.md
[Preview `README` here!](https://github.com/Jint-lzxy/nvimdots/blob/prepare/v1.0/README.md)
I have completely rewritten/reorganized README for v1.0.0 release. It took heavy inspiration from CharlesChiuGit's README, many thanks!
Comments and suggestions are very welcome 👍
_(p.s., Shall we remind users to read the release notes for v1.0.0 _(thru `vim.notify`)_? They need to do some cleanups for packer/Windows users can use the install script to correctly booststrap this config and its deps again;)_
_(p.p.s, We might also need to add install instruction for Windows/edit shots on external links like [zhihu](https://zhuanlan.zhihu.com/p/382092667))_
> refactor(README)!: Rewrite README

- lua/keymap/bind.lua
Adding annotations for keybind lib for ease-of-use
> types: add annotations to keybind lib

- lua/modules/configs/ui/alpha.lua
Migrate alpha to use Lua callback
> refactor(alpha): migrate to Lua API

- lua/core/event.lua
> events: quitting file type with q per pattern

- lua/core/event.lua
> fix: use `vim.keymap.set` for filetype

- lua/modules/configs/completion/lspsaga.lua
- lua/modules/configs/ui/lualine.lua
- lua/modules/utils/init.lua
This PR will be marked as ready for review after changes are merged upstream 👍
> chore(lspsaga): migrate to v0.2.7

- scripts/install.ps1
- scripts/install.sh
Turns out that `Prompt` is a [pwsh built-in](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_prompts) 😢 This PR also unifies function names for all platforms.
> fix(script-win): initialize user functions correctly

- lua/modules/configs/completion/cmp.lua
Per https://github.com/zbirenbaum/copilot-cmp/issues/45
> fix: copilot ignore indent

- lua/keymap/completion.lua
- lua/modules/configs/ui/gitsigns.lua
> refactor(keymap): convert single-mode to multi-mode where possible

- lua/core/options.lua
- lua/keymap/tool.lua
- lua/modules/configs/editor/better-escape.lua
- lua/modules/plugins/tool.lua
See https://github.com/ayamir/nvimdots/issues/615#issuecomment-1500265871.
This resolves #533 and closes #615.
> fix(which-key): properly handle continuous user input

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/lsp_issue_report.yml
1. add discussions link
2. add wiki link
3. add 0.9 tag and deprecate 0.7
> perf: better guidance to `Discussions` and `Wiki`

- lua/modules/configs/ui/bufferline.lua
- lua/modules/utils/init.lua
Ref: upstream breaking change \[ https://github.com/catppuccin/nvim/commit/7a7a6646769e0c0be5d443cf55c04970f90fd230 \]
> fix(catppuccin): properly detect `g:colors_name`

- lua/core/settings.lua
https://github.com/ayamir/nvimdots/discussions/708
> chore(settings): replace `pright` with `jedi_language_server`.

- lua/keymap/editor.lua
- lua/modules/plugins/editor.lua
Ref: https://github.com/rmagatti/auto-session/commit/a2cc591c7e4f742ffc7321bf1d46090c8b2c48bf
> fix(auto-session): fix command names

- lua/core/init.lua
> chore(wsl): use Windows native way to yank and paste.

- lua/modules/configs/ui/neodim.lua
- lua/modules/utils/init.lua
> fix(neodim): prevent `blend_color=NONE` when set trans_bg to true, close #758

- lua/core/settings.lua
- lua/modules/configs/editor/bigfile.lua
* https://github.com/LunarVim/bigfile.nvim/commit/67a03ff3dfbfacaa0b006c7ddc55356c85510b25
* https://github.com/LunarVim/bigfile.nvim/commit/7bf45d6a869a04e60dd20c76b63156e2079aabb2
> pref(bigfile): upstream changes

- lua/modules/configs/ui/scrollview.lua
[nvim-scrollview#signs](https://github.com/dstein64/nvim-scrollview#signs) and https://github.com/ayamir/nvimdots/discussions/494#discussioncomment-6076909
> feat(scrollview): enable signs support

- lua/core/pack.lua
> fix(ui): sync lazy's colorscheme with settings.

- lua/core/init.lua
- lua/modules/configs/completion/inlay-hints.lua
It turns out my issue https://github.com/ayamir/nvimdots/issues/866 is caused by two reasons. One is from rainbow and can be sloved by https://github.com/ayamir/nvimdots/pull/868, the other one is https://github.com/neovim/neovim/issues/23725 and have a workaroud https://github.com/neovim/neovim/issues/23725#issuecomment-1561364086
> workaroud for watchfile problem

- lua/modules/configs/completion/null-ls.lua
This fixes #666.
cc @CharlesChiuGit
> feat(null-ls): usercmd `:NullLsToggle` to toggle sources

- lua/modules/configs/editor/treesitter.lua
https://github.com/ayamir/nvimdots/pull/848#issuecomment-1646772691
> chore(treesitter): cleanup

- lua/modules/configs/completion/lspsaga.lua
I re-align the options with the order of https://dev.neovim.pro/lspsaga/ and update the config
> perf(lspsaga): align options with official doc and update config

- lua/core/event.lua
- lua/modules/utils/keymap.lua
> fix(dap-keymap): local-mapping issues on nvim nightly

- lua/modules/configs/ui/bufferline.lua
https://github.com/akinsho/bufferline.nvim/issues/71#issuecomment-812036951
> bufferline: disable enforce_regular_tabs to fix unique name not working

- lua/modules/configs/editor/autoclose.lua
https://github.com/ayamir/nvimdots/pull/916#issuecomment-1667640540
> revert(autoclose): temporal fix for regression introduced by #916

- lua/modules/configs/editor/autoclose.lua
As per https://github.com/m4xshen/autoclose.nvim/commit/11b60d807496de06e43a091fa4bd11875b49a9c3
> feat(rust): introduce autoclose for operator<

- lua/core/pack.lua
> fix(pack): erroneous searcher for user configs

- lua/core/init.lua
- lua/core/settings.lua
This PR added several comments to help avoid potential issues, and also created Lua annotations for `gui_config` and `neovide_config` to help users identify obvious syntax errors / typos.
> chore(gui-settings): more annotations and minor cleanup

- lua/modules/configs/editor/treesitter.lua
- lua/modules/configs/editor/ts-context-commentstring.lua
- lua/modules/plugins/editor.lua
Ref: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/commit/5b02387b28a79c61b7d406c2a33d4db1d8454f53
> feat(ts-context-commentstring)!: setup as a plugin

- lua/modules/configs/ui/alpha.lua
> feat(icon): use `neovim` icon in nerdfont v3.1.0

- lua/modules/plugins/editor.lua
#1092 
fyi, https://github.com/HiPhish/rainbow-delimiters.nvim/issues/73
> fix(rainbow-delimiters): ping commit until author fix it. ( #1092 )

- lua/modules/plugins/editor.lua
https://github.com/HiPhish/rainbow-delimiters.nvim/issues/73#issuecomment-1852908843
> chore(rainbow-delimiters): update to latest master

- lua/keymap/tool.lua
See: https://github.com/akinsho/toggleterm.nvim/issues/63
> fix: input delay in terminal mode

- lua/modules/plugins/ui.lua
https://github.com/ayamir/nvimdots/pull/1139
https://github.com/ayamir/nvimdots/discussions/1138
cc @ClSlaid
> chore(neodim): remove pin commit (#1139 #1138)

- lua/modules/configs/lang/rust.lua
See https://github.com/mrcjkb/rustaceanvim/commit/819ae2d889cca667e7410341c48955043be100a0 lmao
> fix(rust): follow upstream changes

- .github/workflows/update_lockfile.yml
see https://github.com/andstor/file-existence-action/pull/144
> chore(ci): bump deps versions

- lua/modules/configs/editor/diffview.lua
- lua/modules/plugins/editor.lua
#1168 
@ycpss91255 The correct config should be:
```lua
return {
file_panel = {
win_config = {
position = "right",
},
},
}
```
> feat: make diffview configurable.

- .github/dependabot.yml
This reverts commit 45a53eecfe7b44626fbccb066f35cc92f6378948. #1174
> Revert "feat(ci): use dependabot to bump deps versions (#1174)"

- lua/modules/plugins/completion.lua
https://github.com/ayamir/nvimdots/issues/1183#issuecomment-1966055834
https://github.com/nvimtools/none-ls.nvim/commit/793c6071621814c61a14c24cdb43e9badd88f0af
cc @buptlibo
> chore(none-ls): add option to suppress warning

- lua/modules/configs/completion/null-ls.lua
https://github.com/ayamir/nvimdots/issues/1183
> fix: deprecate rustfmt for none-ls.

- scripts/install.ps1
- scripts/install.sh
1. #1191 reminds me that the install script should also support nightly branch.
2. refactor code.
Tests passed on my Arch wsl2 and Windows11.
> feat: support nightly branch for install script.

- lua/modules/configs/tool/dap/clients/python.lua
https://github.com/ayamir/nvimdots/discussions/1204
> fix: make debugpy work normally on windows.

- lua/modules/configs/completion/cmp.lua
- lua/modules/configs/completion/servers/lua_ls.lua
> fix(lua_ls): disable diagnostics for undefined-field

- lua/core/settings.lua
- nixos/neovim/default.nix
1. add `jsonc` for treestiiter checkhealtch
2. fix sth for nix
> chore: minor patches

- lua/modules/configs/completion/cmp.lua
> fix: set cmp preselect to none.

- scripts/install.ps1
- scripts/install.sh
I recently refactored my frequently used commands and thought it would be great to also port that here lol
> feat(scripts): update frequently used functions

- lua/core/options.lua
As per https://github.com/ayamir/nvimdots/issues/1259#issuecomment-2153851234.
> feat: support new options

- lua/modules/configs/completion/lspsaga.lua
As per [`:h diagnostic-signs`](https://neovim.io/doc/user/diagnostic.html#diagnostic-signs).
> feat(lsp): correctly configure diagnostic-signs

- lua/core/init.lua
> feat(core): use the lua API to set options

- lua/core/event.lua
_No description provided._
---
> fix(events): avoid name clashes

- lua/modules/configs/ui/gitsigns.lua
See https://github.com/lewis6991/gitsigns.nvim/commit/3d7e49c201537ee0293a1a3abe67b67f8e7648a5
---
> fix(gitsigns): upstream breaking changes

- lua/keymap/tool.lua
- lua/modules/configs/completion/cmp.lua
- lua/modules/configs/tool/search.lua
- lua/modules/configs/ui/alpha.lua
- lua/modules/utils/icons.lua
> Revert "Feat/telescope collections keymaps"

- lua/modules/configs/completion/cmp.lua
https://github.com/ayamir/nvimdots/pull/1309#issuecomment-2198430840
> fix(cmp): occasional inability to select completion items

- README.md
We should correct the current startup time.
> docs: update startup time.

- lua/modules/configs/editor/persisted.lua
Ref: https://github.com/olimorris/persisted.nvim/discussions/145
> feat(persisted): update for recent code rewrite

- lua/core/settings.lua
As per: https://github.com/neovim/nvim-lspconfig/commit/bdbc65aadc708ce528efb22bca5f82a7cca6b54d.
> feat(lsp): `tsserver` renamed to `ts_ls`

- lua/core/init.lua
> support overriding `settings.gui_config` with an empty table

- lua/keymap/completion.lua
- lua/modules/configs/completion/formatting.lua
> feat: add Format command and mapping (#1378).

- lua/modules/configs/ui/edgy.lua
- lua/modules/utils/init.lua
This patch add a option `overwrite` when load table kind user config to save code.
> fix: support overwrite when merge config.

- lua/keymap/ui.lua
https://github.com/lewis6991/gitsigns.nvim#keymaps
> fix(keymap.ui): update gitsign keymaps

- lua/modules/configs/editor/local-highlight.lua
introduced in tzachar/local-highlight.nvim#31
> chore(editor.local-highlight): disable animation

- lua/modules/configs/completion/servers/gopls.lua
ref: https://github.com/golang/tools/blob/33f1ed9242128736ca381ce86d10a5fc479aab4c/gopls/internal/settings/settings.go#L188
> fix: update gopls config.

- lua/modules/configs/editor/cursorword.lua
- lua/modules/configs/editor/local-highlight.lua
- lua/modules/configs/ui/catppuccin.lua
- lua/modules/plugins/editor.lua
- lua/modules/utils/init.lua
Saw this [reddit comment](https://www.reddit.com/r/neovim/comments/1ix6g5f/comment/meo89tl/) and realized we don't rlly need all the extra features (esp. after a recent config break). Keeping it simple™ lol
> feat(plugins): replace local-highlight with mini.cursorword

- lua/modules/configs/lang/crates.lua
> fix(crates): remove invalid options.

- lua/modules/configs/editor/grug-far.lua
- lua/modules/configs/tool/fcitx5.lua
- lua/modules/configs/ui/splits.lua
This commit got rid of some legacy configs that literally did nothing (fr this time lol).
> chore(configs): remove useless legacy configs

- lua/modules/configs/completion/cmp.lua
- lua/modules/configs/editor/rainbow_delims.lua
- lua/modules/configs/editor/treesitter.lua
This commit removes all previous performance restrictions as treesitter now supports full asynchronous parsing.
> feat(treesitter): remove performance limitations

- lua/modules/plugins/tool.lua
The original plugin author hasn't updated this plugin for two years. So I tend to fix it by myself.
> fix: replace project.nvim with newest apis.

- README.md
- scripts/install.ps1
- scripts/install.sh
This PR update the branch name in install scripts and readme. The legacy branch will be 0.10 now and we can drop the 0.8 branch.
> fix: support for new branch name.

- lua/modules/configs/completion/lsp.lua
- lua/modules/configs/editor/persisted.lua
It's not fully resolved. The problem still exists when open neovim with restored session. There are many lsp related changes: https://github.com/neovim/neovim/releases/tag/v0.11.2, I will check them on the weekend.
> fix: remove manual `LspStart`, close #1478.

- lua/core/settings.lua
1. update link for `nvim-lspconfig`
2. remove duplicated setting entry: `search_backend`
> chore: some minor clean up

- lua/modules/plugins/tool.lua
ive been using this fork for a while now, and since the author acc put in the work to port over a bunch of the stale PRs, it just makes more sense to use it. Plus this way @ayamir doesn't have to keep maintaining it just to keep stuff working too (looking at u [lsp-signature](https://github.com/Jint-lzxy/lsp_signature.nvim) lol)!
> feat(plugins): replace ayamir/project.nvim with DrKJeff16/project.nvim

- README.md
1. update shots
2. make all shots stored in `ayamir/nvimdots-imgs`
> docs: update readme shots

- lua/modules/configs/completion/lsp.lua
- lua/modules/configs/completion/mason-lspconfig.lua
- lua/modules/configs/editor/persisted.lua
- lua/modules/plugins/completion.lua
This pr still has a problem:
For `lua_ls`, the settings won't come into effect when open `nvim` with filename or session.
> fix: LSP start logic

- lua/core/settings.lua
- lua/keymap/completion.lua
- lua/keymap/tool.lua
- lua/modules/configs/tool/search.lua
- lua/modules/plugins/tool.lua
was tryna merge the `search_backend` support (super cool fr!) into my config rn and made some tweaks to optimize a lil cuz a lot of it is on hot paths so these should help (like using `vim.uv` is almost always better unless maybe we want to talk to `libc` directly)
> refactor(tool): simplify fzf-lua usage and improve lazy loading

- lua/modules/configs/tool/project.lua
> fix(project_nvim): rename module name to project
