- lua/core/global.lua
Before this, `path_sep` was '/' in windows, which is correct in linux or mac.
> [core] fix `path_sep` in global.lua for windows

- lua/modules/editor/plugins.lua
I find the main use nvim-comment no setting
If not setting,the nvim-ts-context-comment is not work
I read origin readme,add the setting to fix this
I try it,now the vue comment can work.
> fix comment-ts-context-commentstring

- plugin/nerdline.lua
I found a problem in your nerdline.lua file. When I press `R` in vim (replace mode), the error appears 
`error: attempt to concatenate a nil value; invalid expression: luaeval('require("galaxyline").component_decorator')("VIMode")`
The colors you define with `R` was colors.violet.(line 79 / 80) But in `colors`(line11) :
```
local colors = {
bg = '#fafafa',
line_bg = '#f0f0f0',
fg = '#2e3440',
fg_green = '#8fbcbb',
yellow = '#ebcb8b',
cyan = '#88c0d0',
darkblue = '#5e81ac',
green = '#a3be8c',
orange = '#d08770',
purple = '#b48ead',
magenta = '#a626a4',
blue = '#81a1c1',
red = '#bf616a',
mode_bg = '#f0f0f0'
}
```
the `violet` property wasn't defined. So the problem appeared. I added violet property in colors and then the bug fixed.
> fix: missing color property in plugin/nerdline.lua (coc branch)

- lua/modules/completion/lspconfig.lua
Ref: [lspconfig/clangd.lua](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/clangd.lua)
```lua
-- https://clangd.llvm.org/extensions.html#switch-between-sourceheader
local function switch_source_header(bufnr)
bufnr = util.validate_bufnr(bufnr)
local params = { uri = vim.uri_from_bufnr(bufnr) }
vim.lsp.buf_request(
bufnr,
'textDocument/switchSourceHeader',
params,
util.compat_handler(function(err, result)
if err then
error(tostring(err))
end
if not result then
print 'Corresponding file cannot be determined'
return
end
vim.api.nvim_command('edit ' .. vim.uri_to_fname(result))
end)
)
end
```
> fix clangd switch source header failed

- lua/modules/completion/plugins.lua
Author of neovim plugin andersevenrud/cmp-tmux has changed the main branch from compe-tmux to cmp-tmux. Therefore, it is necessary to make some change for PackerSync to work as expected.
> fix (/lua/modules/completion/plugins.lua) cmp-tmux name

- lua/modules/completion/config.lua
nvim-cmp removed default mappings on Apr 13, 2022
> fix: nvim-cmp removed default keymap.

- .luarc.json
- lua/modules/completion/lsp.lua
原因是传入设置的时候 `settings` 打成了 `setttings` ww
> 修复：lua 语言服务器无法正确识别和加载 `lspconfig` 传入的设置

- lua/modules/editor/config.lua
- lua/modules/editor/plugins.lua
related issue: #112 
have tested on my Linux (with `fcitx5` installed) and MacOS (need install `im-select` first)
> feat: Add brglng/vim-im-select to change input method automatically.

- lua/modules/tools/config.lua
Related issue: https://github.com/gelguy/wilder.nvim/issues/105 :
> I am afraid it might be related to [28b26ff](https://github.com/gelguy/wilder.nvim/commit/28b26ffa8c3a8bdc34e00bc971199d1bfba30c8f). After adding
> 
> ```viml
>     \   'apply_incsearch_fix': v:true,
> ```
> 
> in the config for `wildmenu_renderer` (see commit [Gelio/ubuntu-dotfiles@cf03f95](https://github.com/Gelio/ubuntu-dotfiles/commit/cf03f95a482ce2b5bda9b5f70eb8e822c025fba1)), the flickering is gone.
**This method has a DRAWBACK** which is described in `wilder`'s README:
> ### Cannot scroll through `/`-search history with `<Up>` or `<Down>`
>
> A workaround was added for https://github.com/gelguy/wilder.nvim/issues/30.
> This workaround breaks the `/` history when using the `wilder#wildmenu_renderer()`.
> fix: incsearch compared with wilder cause highlight flicker

- lua/modules/completion/lsp.lua
- lua/modules/lang/config.lua
Tell `lspconfig` to use `gopls -remote=auto` to avoid spawning two `gopls` server processes. (One by `LSP` and another by `vim-go`)
> fix: disable completion by vim-go, use `gopls -remote=auto` for lsp

- lua/modules/ui/config.lua
如果没理解错的话（ https://github.com/kyazdani42/nvim-tree.lua/issues/674 ）
> nvim-tree.lua once used global variables to define options. These have been moved into **setup options.**
nvim-tree的全局变量`vim.g.`应该迁移到`setup`的表里面（
顺带改了一个拼写错误233（`symlink_arror -> symlink_arrow`）
> Fix (lua/modules/ui/config.lua) Setup configurations of nvim-tree

- lua/modules/editor/config.lua
[dapui](https://github.com/rcarriga/nvim-dap-ui)的最新版本弃用了`sidebar`和`tray`的选项。在执行`<leader>ps`后将看到：
> The 'sidebar' and 'tray' options are deprecated. Please use ' layouts' instead.
详见[作者示例](https://github.com/rcarriga/nvim-dap-ui/blob/52f4840cb95e6638f18a74b71b536c3bd12e9fd8/README.md?plain=1#L74-L94)
> Fix (lua/modules/editor/config.lua) Setup options for dapui

- lua/modules/completion/config.lua
https://github.com/windwp/nvim-autopairs/commit/469ef47fc277e168bfc3e7496442718b2fa1eb1b 调整了部分项目结构。因此更改了设置避免`packer.nvim`报错（例如`cmp_autopairs.lisp`表会是`nil`）
> Fix (lua/modules/completion/config.lua) Setup options for nvim-autopairs

- lua/core/init.lua
- lua/core/options.lua
Generally speaking, some packages needed by `neovim` are installed in the system default python environment, but the `check_conda()` function sets the `neovim` python path to the python in the `conda` environment, which can easily cause errors for some plugins.
> Clear neovim python interpreter setting

- lua/modules/editor/config.lua
- lua/modules/editor/plugins.lua
- Delete `dap-buddy` plugin since mason.nvim
- Adjust dap plugins order
> Fix warning of dap plugins

- lua/modules/editor/plugins.lua
See https://github.com/ayamir/nvimdots/pull/172 for detailed discussion.
The current configuration will **not** affect startup time anymore.
> fix(nvim-dap & dapui): Lazyload and integrations for DAP.

- lua/keymap/bind.lua
- lua/keymap/config.lua
- lua/keymap/init.lua
- lua/modules/editor/config.lua
- lua/modules/editor/plugins.lua
I found `toggleterm.nvim` is functional for all the use cases in this config. So I remove `split-term` and `FTerm.nvim`, leaving `toggleterm.nvim` the only terminal wrapper. Details below:
- Although not being used, I've enhanced `pbind.nvim_load_mapping(mapping)` to allow setting keymap on a specific buffer (`0` represents the current)
- Add global function `_G.toggle_lazygit` to toggle the `lazygit` floating window.
- ~~We are not able to switch to normal mode (with `<C-\><C-n>`) in terminal if we use the default keybinding `<C-\>` to toggle the horizontal terminal. So I change it to `<C-=>`, `=` is next to `\`, easy to get used to~~
- Make the plugin being loaded on "UIEnter" event, in case we want to use the terminal before editing any file.
> Use toggleterm for horizontal,vertical and float terminals, plus lazygit ;)

- lua/modules/ui/config.lua
This commit **intentionally** prevents the background for parentheses from covering other texts / background when `transparent_background` is set to `false`.
**Before:**
**After:**
> fix(catppuccin): Disable background for ts-rainbow.

- lua/modules/ui/config.lua
This commit update [nvim-tree](https://github.com/kyazdani42/nvim-tree.lua)'s options from upstream. Some configs are modified from nvim-tree's recent commits to ensure that this configuration still works correctly. _(For example, `folder_arrow = false` is set to ensure proper alignment)_. However, there are no changes to the existing options _(i.e., the appearance does not change)_.
There're also several cleanups, that's, for example, using `default` instead of `["default"]` for consistency _(L668-690)_
> See [:help nvim-tree-setup](https://github.com/kyazdani42/nvim-tree.lua/blob/master/doc/nvim-tree-lua.txt) for changes and options in detail.
> chore(nvim-tree): Update options from upstream.

- lua/modules/completion/lsp.lua
- lua/modules/ui/config.lua
- lua/modules/ui/plugins.lua
As mentioned in #188. This PR would also close #188 once merged.
- Note that we replace `nvim-gps` with `nvim-navic` in _most_ cases, but gps is still preserved for Treesitter fallback _(i.e., for filetypes / servers that are unsupported by nvim-navic)_
- Catppuccin's integration with navic is also enabled for nice-looking highlights.
- The icons for navic came from nvim-cmp.
**Minor Change**
- Disabled highlight settings for aerial of catppuccin
> feat: Use nvim-navic for showing code context.

- lua/modules/completion/config.lua
**TL;DR The icon set for lsp diagnostic symbols on sidebar is now being controlled by nvim-upstream directly.**
> For detailed explanation, visit https://github.com/glepnir/lspsaga.nvim/issues/428.
> chore(lspsaga): Enable diagnostic symbols for sidebar.

- lua/modules/completion/config.lua
This commit update icons for lspkind _(lspsaga)_ so that they stay consistent with `cmp` and `navic`.
> chore(lspkind): Update icons for consistency.

- lua/modules/completion/lsp.lua
There've been updates to `clangd (llvm, 13 - 14)` that modified the method to pass args to the lsp.
**TL;DR: We need to use the `cmd` table to pass clangd's arguments and set command-line arguments of the compiler (e.g., `clang++`) via clangd's configuration file in the source tree or an OS-specific directory. For most cases, `--query-driver` MUST be set so that clangd can correctly parse system's includes (e.g., for using `#include<type_traits>`), especially when the user doesn't provide `compile_commands.json` or `compile_flags.txt`.**
*****
Configuration is stored in YAML files. These are either:
- **project configuration**: a file named `.clangd` in the source tree. _(clangd searches in all parent directories of the active file)_.
- Generally this should be used for shared and …
> fix(clangd[lsp]): Args aren't being passed correctly.

- lua/modules/completion/lsp.lua
See #193. Clangd comes with `--clang-tidy` support, so there's no need to spawn clang-tidy using efm again.
> chore(efm): Deprecate clang-tidy linter due to usage of clangd.

- lua/modules/editor/plugins.lua
Currently `ts-rainbow` would be loaded **after** treesitter during startup **AND** during the event: `BufReadPost`, which could lead to highlight problems _(e.g., the highlights set by catppuccin will have no effect)_.
> fix(ts-rainbow): Lazy-load event.

- lua/modules/completion/lsp.lua
- lua/modules/editor/config.lua
- lua/modules/editor/plugins.lua
[vim-illuminate](https://github.com/RRethy/vim-illuminate) was updated a few hours ago. This commit migrates all configs to `V2 (nvim)` version. See illuminate's repo for details.
**Note that:** The default appearance for _illumination_ is now underlined (`hi def IlluminatedWordText gui=underline` from source code), and I use:
```lua
local illuminate_bg = string.format("#%06x", vim.api.nvim_get_hl_by_name("Visual", true).background)
```
to restore the original way of display using the `Visual` highlight. This was the default in `V1` and `string.format("#%06x", ...)` is being used because the numbers returned by nvim api are color codes in **decimal**. We can convert them to 6 digit hexadecimal with formatting specifier: `%06x`.
> chore(vim-illuminate): Migrate to V2.

- lua/modules/completion/plugins.lua
[antoinemadec/FixCursorHold.nvim](https://github.com/antoinemadec/FixCursorHold.nvim) is **STRONGLY RECOMMENDED** by almost every plugin that uses the events: `CursorHold` or `CursorHoldI` due to a performance bug _(these events are blocked by timer_start())_, which means some behaviors would have no effect without this fix. See issue #12587 of neovim upstream for details.
> fix: CursorHold integration with lspsaga.

- lua/modules/completion/config.lua
Luasnips snippets dynamic node can be triggered after undo operation
Related to https://github.com/L3MON4D3/LuaSnip/issues/238.
Maybe this issue can be reproduced by contributors.
> fix: add and change luasnips option <delete_check_events>

- lua/modules/ui/config.lua
- `nvim-tree` doesn't require nested options any more.
- Enabled nested options for `bufferline`.
- Update hl group `bufferline` so that the highlights stay consistent with `native-lsp`'s configs.
> chore(catppuccin): Update options from upstream.

- lua/modules/ui/config.lua
This commit removed unnecessary parameters from bufferline's `disgnostics_indicator` function so as to suppress warnings.
> style(bufferline): Cleanup.

- lua/modules/ui/config.lua
This is a known bug of `lualine` _(Bug: Git diagnostic diff (+ ~ -) disappears after vim.diagnostic.* is called)_, current work-around is to use `gitsigns` as source for git diff.
> Fix(lualine): Git diffs aren't rendered in some cases.

- lua/modules/ui/config.lua
Minimum log level is set for nvim-notify so that some notifications won't be ignored and made it user-customizable.
> fix(notify): Set minimum log level support.

- lua/core/pack.lua
- lua/modules/completion/formatting.lua
This commit refactored most of the messages thrown by `notify`, with a _more_ human-readable style and title support. Some log levels are changed for cognitive understanding consistency.
There's also a functional change in `lua/modules/completion/formatting.lua`, here's the summary:
- The `SelectedFormatToggle` command was changed to `FormatterToggle` for consistency and better-understanding.
- The processing logic was changed -- the `if` statement shouldn't terminate that early with `return` - otherwise there could be cognitive problems.
- Use notify instead for message prompt.
<details>
<summary>Diff <i>(for the <code class="notranslate">FormatterToggle</code> section)</i></summary>
<p>
```diff
diff --git a/lua/modules/completion/formatting.lua b/lua/modules/completion/formatting.lua …
```
> refactor(messages): Update notification messages.

- lua/modules/completion/config.lua
I've fixed the upstream problem with `custom_kind`, now we can use that instead for setting icons.
The colors came from [catppuccin's integration with Aerial](https://github.com/catppuccin/nvim/blob/main/lua/catppuccin/groups/integrations/aerial.lua). Fallbacks have been set that utilizes lspsaga's default palette in case the `catppuccin` palette isn't being used.
> refactor(lspsaga): Use `custom_kind` instead for icons.

- lua/modules/ui/config.lua
If `custom_bg` was not set then we could get a strange-looking white background or no highlight.
> fix(catppuccin): Integration with navic.

- lua/modules/ui/config.lua
Ref: https://github.com/ayamir/nvimdots/pull/212#issuecomment-1229195013. As usual, we still retain maximum compatibility with other colorschemes. Catppuccin's special configs are overwritten by:
```lua
opts = vim.tbl_deep_extend("force", opts, catppuccin_hl_overwrite)
```
**We might need to update the wiki for this change. I'll document this asap.**
> feat(catppuccin & bufferline)!: Move configs in place.

- lua/modules/tools/config.lua
> Ref: https://github.com/ayamir/nvimdots/commit/281a60b180d39fe89536d94a347a38dd1d1914d5, https://github.com/ayamir/nvimdots/issues/218
I've added even more file ignore patterns for telescope. Those pre/suffixes are common file extensions or folders that either couldn't be edited in neovim _(e.g., `%.pdf`)_ or shouldn't be included in the list _(e.g., `.cache`)_.
> chore(telescope): Added even more ignore patterns.

- lua/modules/editor/plugins.lua
> This reverts commit a8aa909baeb844848d4d30050d1884d38611ef2b, reversing changes made to 3b9d470b41414089f2b3022232dd1a8d69ec1089.
Ref: https://github.com/nvim-treesitter/nvim-treesitter-textobjects/commit/be98836bf0de595c3d8dd6d5e4b2f5d68483631d. The visual mapping problem has been resolved.
> chore: Remove commit restriction for ts-textobjects

- lua/modules/completion/efm/formatters/clangfmt.lua
- lua/modules/completion/lsp.lua
This is a better _(and possibly clearer and easier to maintain)_ option for importing user-specific configs for efm, and might be the original design pattern as well.
> chore(efm[lsp]): Load options using modules.

- .github/workflows/format_check.yml
- .github/workflows/style_check.yml
- lua/modules/completion/efm/formatters/rustfmt.lua
- stylua.toml
It would be a great idea to enable **CI** _(in this case, code style check)_ for PRs and pushes to ensure consistency in coding styles. All files have been formatted using stylua again for successful workflow run.
**IMPORTANT NOTE:**
- Go to `Settings -> Branches -> Branch protection rules -> Edit Rule` _(possibly called main)_ and tick **require status checks to pass before merging**, choose this new action and we're all set lol.
Current status:
[![style check](https://github.com/Jint-lzxy/nvimdots/actions/workflows/style_check.yml/badge.svg?branch=ci)](https://github.com/Jint-lzxy/nvimdots/actions/workflows/style_check.yml) <--- For those coming afterwards, this badge would be invalid after a successful merging and branch cleaning.
> feat(workflow & stylua): Enable CI (code style check)

- lua/modules/completion/config.lua
Currently, the `<C-h>` and `<C-l>` mappings used to navigate between snippet sections could conflict with other mappings in the most hidden area _(for example, in extreme cases, typing `<C-h>` may cause the character after the cursor to be deleted_ [a.k.a., invoking `<BS>`]_)_. This commit modified this behavior and enabled what's called _super-tab-like mapping_, which uses `<Tab>` and `<S-Tab>` to handle all navigation requests. See the code for implementation details.
> chore(luasnip & cmp): Fix broken keymaps.

- lua/modules/tools/plugins.lua
After this commit, no matter which key the user sets as `<leader>`, which-key.nvim will always be loaded when appropriate.
> chore: Allow generic `<leader>` keybinding for lazy-load.

- .github/workflows/style_check.yml
This commit fixed the problem with formatting CI. Currently incorrect artifact was chosen due to the introduction of `linux-aarch64` artifacts of latest `stylua-action` _(a.k.a, `v1.1.0`)_, which would cause "ELF not found" related errors.
> Ref: https://github.com/JohnnyMorganz/stylua-action/releases/tag/v1.1.1
> fix(CI): Broken workflow (ELF not found).

- lua/modules/editor/config.lua
DAPInstall was replaced by mason and removed in #169 , but the python configuration of nvim-dap stays unchanged. 
The official tutorial [Debug Adapter installation](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#python) recommends using virtual environment, but I think the easiest way is either applying [nvim-dap-python](https://github.com/mfussenegger/nvim-dap-python) or using `/usr/bin/python` by `pip install debugpy` directly. In this PR I use the latter and it works fine in archlinux. What do you think of it?
BTW [wiki](https://github.com/ayamir/nvimdots/wiki/Plugins#editor) also needs to update, but it seems that only repo owner can edit.
> fix: invalid path in dap python configuration.

- lua/modules/editor/config.lua
- Treesitter parser for help doc is currently having some issue for conceal https://github.com/neovim/tree-sitter-vimdoc/issues/23.
> (temp) fix: Disable Treesitter highlight on help pages.

- lua/core/pack.lua
This PR fixes the Packer bootstrap issue that may happen in the 0.8 branch.
Signed-off-by: ClSlaid <cailue@bupt.edu.cn>
> fix packer bootstrap issue in 0.8 branch

- lua/core/pack.lua
sometimes `packer.nvim` may fail to cache compiled lua file in data_dir.
This PR ensures the cache file will be compiled.
Signed-off-by: ClSlaid <cailue@bupt.edu.cn>
> fix packer bootstraping

- lua/core/global.lua
- lua/core/init.lua
- lua/core/options.lua
Without setting clipboard configs, nvim will spend extra time(~300ms) to find clipboard provider, according to [this reddit post](https://www.reddit.com/r/neovim/comments/ab01n8/improve_neovim_startup_by_60ms_for_free_on_macos/).
This setup improve startup time from ~400ms to ~40ms on my wsl.
And a more sensible python provider config, for conda especially.
OS: Ubuntu 22.04(wsl)
Nvim: 0.8-dev
PS. Sorry for creating so many pr, I'm not quite familiar with branches.
> Optimize wsl startup time and sensible python provider config. (branch: 0.8)

- lua/modules/lang/config.lua
I noticed that rust_analyzer was configured by rust-tool.nvim plugin, and there is no configuration for lsp_signature.nvim and nvim-navic.
> fix: enable lsp_signature and nvim-navic with rust

- lua/modules/completion/plugins.lua
解决因加载顺序问题导致“mason not found”问题，以防止一些用户在添加新插件之后，PackerCompile容易报错的现象
Signed-off-by: cody <admin@nacgame.com>
> 解决因加载顺序问题导致“mason not found”问题

- lua/modules/editor/config.lua
In the version: NVIM v0.9.0-dev-55-gedc8a1f046, branch 0.8 commit [4a4e9eb](https://github.com/ayamir/nvimdots/commit/4a4e9eb9b3ac1397d0c5e1b40a0998488e4a5d43) will run into an error in this [line](https://github.com/ayamir/nvimdots/blob/4a4e9eb9b3ac1397d0c5e1b40a0998488e4a5d43/lua/modules/editor/config.lua#L442):
Invalid expression on:
```
let g:ImSelectSetImCmd = {
\ key ->
^^------ invalid expression
\ key == 1 ? ['fcitx5-remote', '-c'] :
\ key == 2 ? ['fcitx5-remote', '-o'] :
\ key == 0 ? ['fcitx5-remote', '-c'] :
\ execute("throw 'invalid im key'")
\ }
]])
```
It's suggested in neovim's official documentations that using `nvim_cmd` or `nvim_exec` instead of `nvim_command` on multiple lines of Ex commands, and by replacing it I somehow fixed this problem.
Signed-off-by: ClSlaid …
> fix: im pick up error

- lua/modules/editor/plugins.lua
For the old one is not maintained. And the NvChad one had included some important merge.
> feat: update nvim-colorizer.lua to a new fork

- lua/modules/editor/config.lua
> This issue has been fixed by upstream.
> feat(ts-help): Enable treesitter highlight on help pages.

- lua/modules/completion/lsp.lua
`update_caoabilites` is deprecated, use `cmp_nvim_lsp.default_capabilities` instead.
> chore(lsp): Migrate to `default_capabilities`.

- lua/modules/completion/lsp.lua
A new commit in mason-lspconfig.nvim https://github.com/williamboman/mason-lspconfig.nvim/pull/81 warns about invalid entries in ensure_installed, and I got warnings from `:Notifications` like:
```
Server bash-language-server is not a valid entry in ensure_installed. Make sure to only provide lspconfig server names.
Server lua-language-server is not a valid entry in ensure_installed. Make sure to only provide lspconfig server names.
```
So I replace the server name with name in [available-lsp-servers](https://github.com/williamboman/mason-lspconfig.nvim#available-lsp-servers).
> fix: not a valid entry warning thrown by mason-lspconfig

- install/install.sh
**This commit updated the installation script to ensure cross platform-support _(on \*nix)_.**
The details are as follows:
- All pathnames and variables are now enclosed in quotation marks to prevent installation failure due to space(s) in variables.
- **!!** **Replace** the `sed` command with `perl`. AFAIK `perl` is now provided on `MacOS`, `Unix`, and `Linux` _(Linux reference: [LSB Languages Version 5.0](https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Languages/LSB-Languages/perllocation.html) and [Download page for Perl](https://www.perl.org/get.html))_. This can address compatibility issues of the `sed` command with `-i` option.
@ayamir @CharlesChiuGit Can you help me test this on Linux? I don't have machines running Linux at hand, but AFAIK `perl` _should_ work correctly on every …
> feat(script): Support cross-platform installation on *nix.

- lua/core/mapping.lua
This might be a better solution for #321. With `normal za`, we can still use paragraph folding thru `<S-Tab>`.
Since `CSI u` keycode is not *yet* supported on every terminal, IMO at present, what we can do is to resolve those _conflicting_ keybindings _(\<C-i\> and \<Tab\>)_, rather than completely disable this possibly commonly used feature.
<details>
<summary><code class="notranslate">:h za</code></summary>
<p>
<div class="highlight highlight-text-shell-session notranslate position-relative overflow-auto" dir="auto"><pre><span class="pl-c1">							*za*</span>
<span class="pl-c1">za		When on a closed fold: open it.  When folds are nested, you</span>
<span class="pl-c1">		may have to use "za" several times.  When a count is given,</span>
<span class="pl-c1">		that many closed folds are …
> fix(mapping): Resolve conflicting <C-i> and <Tab> mapping.

- lua/modules/editor/config.lua
- lua/modules/editor/plugins.lua
This commit updated the appearance of `clever-f.vim` to keep it consistent with other colors.
> chore(clever-f): Update highlights and options.

- lua/modules/ui/config.lua
https://github.com/catppuccin/nvim/commit/d1c3eb0409fc74dc685e6d2a576d2004f0113ab8 introduced these changes, which will affect the appearance of `alpha`. Configs have been adjusted accordingly for `mocha`.
> fix(catppuccin): Improve highlight for mocha

- lua/modules/editor/config.lua
Some files will not be highlighted under the current `max_file_lines = 1000` setting. IMO `2000` is a relatively _more_ reasonable value.
> chore(ts-rainbow): Increase highlight threshold

- lua/modules/tools/config.lua
`telescope-ui-select.nvim` was removed in [`e8d2c5b`](https://github.com/ayamir/nvimdots/pull/333/commits/e8d2c5b5277b4aa2002f235c5713a1eb0715856d). However, this plugin is still loaded via `packadd` incorrectly.
> fix(plugins): Remove unintended "packadd"

- lua/modules/ui/config.lua
Due to changes in the upstream _(nvim-treesitter)_ highlight groups, I have also modified several highlights for catppuccin to prevent duplication in adjacent highlight groups _(in some cases, they cannot be distinguished at a glance)_, for example:
```cpp
static constexpr                          foo                     <int> bar;
↑                                    ↑                        ↑
storage_class_specifier/type_qualifier(yellow)    type_identifier(yellow)   primitive_type(yellow, italic)
```
has been adjusted to:
```cpp
static constexpr                          foo                     <int> bar;
↑                                    ↑                        ↑
storage_class/type_qualifier(red, italic)    type_identifier(yellow)   primitive_type(yellow, italic)
```
******
- …
> chore(catppuccin): Update highlights

- lua/keymap/init.lua
- lua/modules/tools/config.lua
see https://github.com/glepnir/lspsaga.nvim/commit/b7b4777369b441341b2dcd45c738ea4167c11c9e
> chore(lspsaga): deprecate LSoutlineToggle, use Lspsaga outline instead

- lua/modules/editor/plugins.lua
When one fires nvim, the colored background of the hex values are oftenly being overide by treesitter. Loading colorizer after treesitter provides a more consistent behavior when working with colors.
> chore(colorizer): prevent treesitter to overide background

- lua/core/event.lua
- lua/core/pack.lua
This autocmd can hot-reload nvim configs when core options being modified. 
Plugins config may or may not work, depends on how plugin read their config.
NOTE: the `~/.config/nvim` must not be a sym-link.
> feat(core): hot reload nvim core options

- lua/modules/completion/lsp.lua
Lsp highlighting is generally slower than treesitter highlighting, which often causes glitter when editing larger files.
TS-highlighting is also more mature and being broadly adopted by most of the plugins, which generally means it's more "prettier".
> chore(lua-lsp): prevent lua-ts highlighting being overwritten by lua-lsp

- lua/modules/completion/lsp.lua
- lua/modules/ui/config.lua
- lua/modules/ui/plugins.lua
The commits resolved:
- Dependency problem of `neodim`
- Rephrased ambiguous comments
- Add option for notify
BTW `project.nvim` and `telescope-project.nvim` provide very similar functions. Is it intentional to keep the two plugins installed at the same time?
> Fixups for neodim & notify

- lua/modules/completion/lsp.lua
I found the default capabilities here: 
https://github.com/neovim/nvim-lspconfig/blob/973aa14d0992df82ff82f714d978a3eb8d676600/lua/lspconfig/server_configurations/clangd.lua#L33
#375
> fix(lsp): use clang default capabilities with utf-16 as the first offsetEncoding option.

- lua/core/event.lua
- lua/core/pack.lua
- lua/modules/completion/formatting.lua
- lua/modules/completion/lsp.lua
This commit revokes the hot-reload feature, removes the settings that `clangd` has deprecated, and cleans up the code.
Related: #377. This would close #375.
> pref: Cleanup unnecessary code

- lua/modules/editor/plugins.lua
- lua/modules/lang/plugins.lua
- lua/modules/tools/plugins.lua
- lua/modules/ui/plugins.lua
This commit made the following changes:
- Packer no longer provides the `wants` option, so the corresponding code is deleted;
- Better specify the dependencies of `neodim`;
- Set `plenary` to load on demand
> perf: Cleanup legacy code

- lua/modules/completion/config.lua
- lua/modules/completion/plugins.lua
- lua/modules/tools/config.lua
- lua/modules/ui/config.lua
- lua/modules/ui/icons.lua
- lua/modules/ui/plugins.lua
- lua/modules/utils/init.lua
https://github.com/ayamir/nvimdots/issues/398#issuecomment-1370423444. This can solve rendering problems such as displaying `'cursorcolumn'`. Symbol_in_winbar will cause the space between bufferline and the file to be inaccessible by built-in features.
This is a rough setup and should require additional testing 👍
> feat(lspsaga & lualine): Show symbols in lualine.

- lua/modules/utils/init.lua
This commit uses recursion to expand highlight linking, and checks the `style` option to ensure that other attributes can also be passed correctly.
> fix(utils): Handle highlight linking properly

- lua/modules/completion/config.lua
`panel` and `suggestion` are default to true.
Also, the copilot suggestion in cmp seems faster after setting it to false.
ref: https://github.com/zbirenbaum/copilot-cmp/commit/b732a58ac8b7287b981cd9f0d9c0f61e5e9d5760
> perf(copilot): disable `panel` & `suggestion` for it can interfere `copilot-cmp`

- lua/core/event.lua
- lua/modules/completion/lsp.lua
- lua/modules/editor/config.lua
- lua/modules/ui/config.lua
- lua/modules/ui/plugins.lua
Fixes #391.
The source of the problem is that `alpha` sets `opt_local.buftype = "nofile"`, which will prevent `nvim-tree` from replacing it _(as `nofile` is in the exclusion list)_.  Someone in the `alpha-nvim` repo has once opened an issue _(https://github.com/goolord/alpha-nvim/issues/114)_, but it has never been resolved.
Detail: https://github.com/ayamir/nvimdots/issues/391#issuecomment-1405086281.
Note: We may need to add some filetypes to the list since the buffers of plugins such as `Man.lua` will be recognized, but they should never be replaced IMO.
> fix(nvim-tree): Replace alpha with the target file

- lua/modules/editor/config.lua
- lua/modules/ui/config.lua
Already defined in `keymap/init.lua`:
https://github.com/ayamir/nvimdots/blob/4327d800db8b9b3777fd8200b5f8bb95ef1e35e1/lua/keymap/init.lua#L143-L145
The default keymap conflicts with `nvim-cmp`.
> fix(tabout): Unset default keymap

- install/install.sh
I've had cases where `neovim` reads incorrect configuration in the same directory, using a special prefix should avoid this situation.
see: https://github.com/ayamir/nvimdots/issues/441
> change backup folder name

- lua/modules/completion/config.lua
- lua/modules/ui/config.lua
This commit makes the config compatible with `lspsaga`@v0.2.4.
Major changes include:
- Codeaction icon is enabled in the sidebar.
- Custom colors are no longer supported, so they have been removed.
- Since the current highlight groups are stable _(they shouldn't change much in the future)_, appropriate configs have been applied for catppuccin-lspsaga.
> chore(lspsaga & catppuccin): Migrate to v0.2.4.

- install/install.ps1
Also a side note:
> 使用chocolatey安装必要的依赖，下载相应的安装包时会检测系统代理，因为大多是从github下载，所以最好开启系统代理。
> _(From `zhihu`)_
In fact, users can choose to use `chocolatey` or `scoop` to fetch deps. TBH, I see more people using `scoop` so I decided to support both of them.
IMO it would be better to address that the script also supports `scoop` _(and users must install one of them before invoking the script)_, otherwise it may lead to confusion. _(ppl probably won't read the code before installation)_
> fix(script-win): Typo

- install/install.ps1
This should eliminate that weird message showing:
```console
cmdlet prompt at command pipeline position 1
Supply values for the following parameters:
Msg:
```
@ayamir @CharlesChiuGit  I would be most grateful if you could test this fix _(let the program exit abnormally, calling `_abort`)_
> fix(script-win): Avoid prompting for user input when failed

- lua/modules/configs/completion/servers/clangd.lua
I added this small change for clangd to auto-complete the tools that is used for --query-driver
Maybe after custom config for users mature a bit more, we can allow them to configure such features as well, but for now if users need to add any new driver they can just add it in the table instead of modifying the specific path.
> chore(clangd): add auto-path completion for query-driver

- lua/keymap/bind.lua
- lua/keymap/init.lua
This PR allows users to map given keybinding with lua callback
Currently, users can achieve setting callback with:
```lua
...
["n|fp"] = map_cu("lua require('telescope').extensions.projects.projects{}"):with_noremap():with_silent(),
...
```
This PR allows the following:
```lua
local map_callback = require("keybind").map_callback
...
["n|fp"] = map_callback(
function()
require('telescope').extensions.projects.projects{}
end
):with_noremap():with_silent(),
...
```
This makes writing keymap feel more natural and programmatically than parsing string.
> feat: mapping lua callback

- scripts/install.ps1
@CharlesChiuGit I'm not sure if this is intentional or not, but the name of the executable for `ripgrep` should be `rg` on all platforms.
```rust
app.gen_completions("rg", Shell::PowerShell, &outdir);
```
[BurntSushi/ripgrep/build.rs#L43](https://github.com/BurntSushi/ripgrep/blob/master/build.rs#L43)
> fix(install-win): Update exec name for 'ripgrep'

- init.lua
- lua/core/options.lua
- lua/modules/plugins/completion.lua
- lua/modules/plugins/editor.lua
- lua/modules/plugins/tool.lua
- lua/modules/plugins/ui.lua
As mentioned in #501.
However, the "user-perceived" startup time _(especially in the case of directly opening a file for editing)_ will be **_greatly_** reduced (Tested on macOS)
@CharlesChiuGit Can you help me double-check whether there're feature breakages?
> feat: Use CursorHold* to improve startup time

- lua/keymap/tool.lua
Otherwise, `_toggle_lazygit()` or `_command_panel()` won't work.
> fix: `keymap.helpers` must be required first

- .github/workflows/update_lockfile.yml
IMO, we don't need the bot to run on per-commit base. 
It's just a wast of computing resources, also it failed sometimes weirdly which is annoying.
> chore(ci): disable updating lazy-lock when push commits

- lua/modules/configs/editor/autoclose.lua
- lua/modules/plugins/ui.lua
Miscellaneous updates, including:
* [perf(paint.nvim): load during `CursorHold`](https://github.com/ayamir/nvimdots/commit/761508c9bd7a858f1d60fc5b8fd46381a6bd5b8d)
* [feat(autoclose): also match `<`](https://github.com/ayamir/nvimdots/commit/897d57cfb7a672301249f7ac1e7920191de410b9)
* [feat(autoclose): disable on large files](https://github.com/ayamir/nvimdots/commit/3e3d2841a02ae82ff8ef65532741082e7e2f57d8)
> Miscellaneous updates

- lua/modules/configs/completion/lsp.lua
Just realized wrapping `require` inside `pcall` would do the trick 😄
> feat(lsp): use `pcall` for error handling

- .github/workflows/update_lockfile.yml
This PR would stop `update_lockfile.yml` from messing up the commit history.
> feat(ci): update lockfile only when there are new commits

- lua/modules/configs/completion/cmp.lua
This PR should resolve #588.
From the documentation:
- `expand_or_locally_jumpable()`: same as `expand_or_jumpable()` **except jumpable is ignored if the cursor is not inside the current snippet**.
> fix: disable luasnip jumps if the cursor isn't inside a snippet

- dots.tutor
- lua/modules/configs/completion/cmp.lua
This commit changes the keymap for `cmp.close` from `<C-e>` to `<C-w>`.
This way:
* Makes the keymap more intuitive and easier to memorize (`<C-w>` --> Close the focused window on most platforms)
* Makes `cmp.close` easier to type _(`w` is closer to `<CTRL>` than `e`)_
As this change does not conflict with `<C-w>` in normal mode, no conflicting keymap was found for the time being.
> pref(cmp)!: update keymap for `cmp.close`

- lua/core/settings.lua
- lua/keymap/completion.lua
- lua/modules/configs/completion/lspsaga.lua
This commit added support for lspsaga v0.2.9. Changes include:
* keymap for `show_line_diagnostics` was changed to `<leader>ld` (previously `<leader>sl`)
* `show_cursor_diagnostics` is deprecated - `<leader>sc` is now unset
* finder: option `edit` --> `expand_or_jump`
* diagnostic:
* new options: `text_hl_follow`, `extend_relatedInformation`, `keys.*`
* hover: `open_link`, default to `gl`
* outline: All options are merged to give `expand_or_jump`
* ui:
* removed entry: `diagnostic`
* added entry: `actionfix` (`ui.Spell`)
> feat(lspsaga): support v0.2.9

- lua/keymap/editor.lua
The original easyalign keymap use `<Plug>(EasyAlign)` , which will not correctly hook lazyloading of easyalign as that's not actually us cmd `EasyAlign`
https://github.com/ayamir/nvimdots/blob/c56cd604dc3b9f7149b89f245206daf0b00b369c/lua/modules/plugins/editor.lua#L48
> fix: easyalign keymap

- lua/keymap/editor.lua
An important feature (to me) of hop.nvim is it support be used in visual mode:
```
Use it with commands like v, d, c, y to visually select/delete/change/yank up to your new cursor position.
```
But the current map only support normal mode.
Weird thing is simply changing it to
```
["nv|<leader>w"] = map_cu("HopWord"):with_noremap():with_desc("jump: Goto word")
```
does not work.
> feat: use hop in visual mode

- lua/modules/configs/completion/cmp.lua
This PR should finally address https://github.com/ayamir/nvimdots/discussions/599.
Looks like LuaSnip regards the situation of "cursor being inside a snippet but unable to jump forward" as `locally_jumpable`. This PR checks whether the jump was successful by determining cursor positions before and after calling LuaSnip.
Here, `vim.schedule_wrap` is used to avoid calling this function before `vim.fn.feedkeys` is evaluated _(`feedkeys()` does not block the main thread)_.
> fix(cmp): handle LuaSnip jump failures

- lazy-lock.json
- lua/modules/plugins/tool.lua
`popup.nvim` is merged into `plenary.nvim`. See [plenary.nvim repository, PR209](https://github.com/nvim-lua/plenary.nvim/pull/209).  
`telescope.nvim` nolonger depends on that package.
> Remove `popup.nvim` from dependencies of `telescope.nvim`

- lua/keymap/tool.lua
> fix: use `with_noremap` in term mode exiting

- lua/modules/configs/completion/lspsaga.lua
- lua/modules/configs/ui/catppuccin.lua
This PR added initial support for lsp semantic tokens. It only implements **a small part** of semantic tokens.
Further development would require testing on more supported languages.
> feat!: add initial support for lsp semantic tokens

- lua/modules/utils/init.lua
> feat(utils): use neovim builtin to get highlights

- lua/modules/configs/ui/alpha.lua
- lua/modules/utils/init.lua
This PR prepares for [**! Refactor Treesitter highlights**](https://github.com/ayamir/nvimdots/issues/627). It separates the highlights for Alpha from those syntax-based highlights.
> feat(alpha): add custom highlight groups

- lua/core/mapping.lua
This commit made the following changes:
- Simplify binding commands (e.g., `map_cmd(":...<CR>") -> map_cr("...")`).
- **Remove** `<leader><leader>x` as this is only available on \*nix-like systems.
- **Remove** `<leader><leader>s` b/c some terminals may not refresh their UI in a _timely manner_ [^1]
[^1]: _The explanation may be a bit complicated, but I will try to keep it concise_:
Since this keymap starts with `<Cmd>`, although `nvim` **interprets** it as `:%s/\<(word-under-cursor)\>/(word-under-cursor)/gI` and **places** that on the command line, some terminals may _still_ refuse to refresh their UI _(usually, instructions starting with `<Cmd>` will **not** be displayed)_. Since we are, however, in command mode at this point, it would be like _typing in the dark_ - those terminals will …
> chore(mapping): cleanup

- lua/modules/configs/ui/paint.lua
Current paint setup falsely recognize word boundary in python
> fix: paint word boundary in python

- lua/modules/configs/ui/bufferline.lua
https://github.com/akinsho/bufferline.nvim/commit/6ccdee8e931503699eb8f92c7faafd0ad1a8cf69
ref: https://github.com/nvim-tree/nvim-web-devicons#get-icon
> fix(bufferline): `show_buffer_default_icon` is now deprecate

- lua/modules/configs/completion/formatting.lua
Changes made _(added L105-109)_:
https://github.com/ayamir/nvimdots/blob/75f4dc858a40fd9ffa27a0c37fc066d385188830/lua/modules/configs/completion/formatting.lua#L104-L111
> feat(formatting): notify users for files under disabled dirs

- lua/core/init.lua
- lua/core/options.lua
1. set default shell from `cmd` to `powershell`.[^1]
2. set `fileendoing` to use `utf-8` only
All screenshots are taken in windows terminal
TODO:
1. ~~icon overlapping~~ (if anyone have this issue, just try another nerdfont)
2. icon won't show in `toggleterm.nvim`, it only works in the neovim built-in terminal.
Results:
[^1]: `pwsh` would be better, but it's not installed on windows by default. Only `cmd` and `powershell` are.
> fix(font-encoding): fix invalid characters on windows, fix #639

- lua/core/settings.lua
- lua/modules/configs/ui/catppuccin.lua
- lua/modules/configs/ui/edge.lua
- lua/modules/configs/ui/nord.lua
add an option in `setting.lua` to set  transparent background conveniently
> chore: update transparent bg settings

- lua/modules/configs/ui/bufferline.lua
This PR partially reverted commit ecaba008ae53e66113f0938a0605416de4d3ec83, fixing a regression.
Under current config _(using custom `get_element_icon`)_, all tabs will have the same icon _(since `vim.bo.filetype` can only hold one valid value)_
> fix(bufferline): use defaults for `get_element_icon`

- lua/core/options.lua
add [recommended options](https://github.com/rmagatti/auto-session#recommended-sessionoptions-config) for auto-session, mainly to remember which buffers I've opened last time
> feat(auto-session): remove customized options

- lua/modules/plugins/editor.lua
close https://github.com/ayamir/nvimdots/discussions/693#discussioncomment-5802367
> feat(nvim-treesitter): add nvim-treesitter-context

- lua/core/settings.lua
> fix(lsp): set default python lsp to `pylsp`, avoid high CPU load caused by `jedi`.

- lua/modules/configs/completion/cmp.lua
This should be the feature requested by the author @namespacebilibili in https://github.com/ayamir/nvimdots/discussions/623#discussion-5052353. I'm not sure if this is compatible with `copilot`.
> feat(cmp): enable `experimental.ghost_text`

- lua/core/event.lua
- lua/keymap/completion.lua
Lsp's keymap should not work when I'm editing a normal file。
> chore(keymap): lsp keymap should effective at `LspAttach` event

- lua/modules/configs/ui/neodim.lua
- lua/modules/utils/init.lua
I'm not sure why `nvim_get_hl` returns a decimal RGB value instead of a hex string.
@ayamir @CharlesChiuGit Have u encountered similar issues?
```lua
:=vim.api.nvim_get_hl(0, { name = "Normal" })
```
Returns
```console
{
bg = 1973806,
fg = 13489908
}
Press ENTER or type command to continue
```
But according to the documentation, it _should_ return:
```console
{
bg = #1E1E2E,
fg = #CDD6F4
}
Press ENTER or type command to continue
```
> feat(neodim): support v2

- lua/modules/configs/editor/auto-session.lua
https://github.com/ayamir/nvimdots/issues/742
> feat: load `SessionLens` manually via user command

- lua/core/init.lua
- lua/keymap/helpers.lua
- lua/modules/configs/completion/lsp.lua
Bug fix for `vim.fn.<bool>` conditional statements.
> fix(vim_fn): check return values of `vim.fn` against 1

- lua/core/settings.lua
- lua/modules/configs/completion/lsp.lua
- lua/modules/configs/completion/null-ls.lua
- lua/modules/configs/completion/servers/pylsp.lua
I set the default config for `pylsp` and solved the problem in https://github.com/ayamir/nvimdots/issues/767 by enable `ruff` to do lint.
Main config:
1. Use [python-lsp-ruff](https://github.com/python-lsp/python-lsp-ruff) to provide lint function due to its high performance.
2. Use [pylsp-rope](https://github.com/python-rope/pylsp-rope) to provide code refactor function in code action's way as mentioned in https://github.com/ayamir/nvimdots/discussions/708#discussioncomment-5890640.
3. Use [python-lsp-black](https://github.com/python-lsp/python-lsp-black) to provide format function.
4. Remove black config in `null-ls`.
5. Users no need to install or update these plugins manually after `pylsp` installed or updated.
The result:
> feat: set default config for pylsp.

- lua/modules/configs/completion/servers/pylsp.lua
https://github.com/python-lsp/python-lsp-ruff/pull/38
Not sure to use "Information" or "Hint", and maybe `settings["diagnostics_virtual_text"] ` should be more controlable so one can define
```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
signs = true,
underline = true,
virtual_text = { require("core.settings").diagnostics_virtual_text, severity_limit = "Warning" },
-- set update_in_insert to false bacause it was enabled by lspsaga
update_in_insert = false,
})
```
> chore(lsp): set lower pylsp severity

- lua/core/settings.lua
- lua/modules/configs/completion/lsp.lua
> feat: make live diagnostics level configurable

- lua/modules/configs/completion/lsp.lua
@nkta3m
The way to reivew this pr:
1. `git pull`
2. `git switch fix/pylsp-deps-for-win`
3. `nvim somefile.xx`
4. `:Mason`
5. `/` to search `pylsp`
6. hold cursor on the line of `pylsp`
7. if installed, press `u`, else, press `i`
8. wait for success notification.
> fix: correct path for pylsp plugins on windows, close #778.

- lua/modules/configs/completion/cmp.lua
`max_view_entries` is used to limit the number of items listed in the _autocomplete list_, so there's no need to set it to such a large value.
> pref(cmp): reduce max entry count to 150

- lua/modules/configs/ui/catppuccin.lua
- lua/modules/configs/ui/indent-blankline.lua
> feat(ui): unify UI component indent-blankline

- lua/modules/configs/editor/nvim-treesitter-context.lua
- lua/modules/configs/editor/ts-context.lua
- lua/modules/plugins/editor.lua
> fix(ts-context): always call `setup` on start (#828)

- lua/core/options.lua
Just found out that we removed `stabilize.nvim` but forgot to set the corresponding option :)
> fix(options): correct scroll behaviors of (h)splits

- lua/modules/utils/init.lua
This PR implemented dynamic palette support for https://github.com/ayamir/nvimdots/issues/698#issuecomment-1614699356.
cc @volpan
> feat(utils): auto-refresh builtin palette on `ColorScheme`

- lua/modules/configs/completion/lsp-signature.lua
- lua/modules/configs/completion/lsp.lua
- lua/modules/configs/lang/rust-tools.lua
- lua/modules/plugins/completion.lua
* `on_attach` [is deprecated](https://github.com/ray-x/lsp_signature.nvim/blob/17ff7a405fea8376b015b8ea7910d2e59958bf68/doc/lsp_signature.txt#L148-L149);
* Now `lsp_signature` won't adjust its position relative to the completion popup to avoid problematic functions (cmp.visible) being called.
> workaround(lsp-signature)!: fix input delay of nvim-cmp

- lua/modules/configs/ui/lualine.lua
This works b/c `finddir()` searches bidirectionally _(downward searches are recursive and may search through many directories)_.
This commit instructs `fs.find` to only traverse upward through parent directories and terminate as long as a match is found.
> perf(lualine): more efficient `has_git` checks

- lua/core/settings.lua
Should we include `rustup` installation in our installation scripts?
Besides `rustfmt`, `sniprun` also needs `cargo` to compile, so I think it might be acceptable to add it.
cc @Jint-lzxy @ClSlaid @volpan
> migrate: install `rustfmt` from `rustup` (#842)

- lua/modules/configs/completion/null-ls.lua
- scripts/install.ps1
- scripts/install.sh
Haven't introduced `rustup` into the install script(s) yet cause I can't figure out how to automate this process 😢
> fix(null-ls): specify `rustfmt` manually

- lua/modules/configs/ui/catppuccin.lua
Close #853
Upstream integration now use you guys's work 😺 https://github.com/catppuccin/nvim/pull/538
[Jint-lzxy/nvim](https://github.com/Jint-lzxy/nvim/tree/refactor/syntax-highlighting) needs to be update first
> feat(catppuccin): use upstream nvchad style

- lua/modules/configs/completion/lsp.lua
- lua/modules/configs/completion/lspsaga.lua
- lua/modules/configs/editor/rainbow_delims.lua
- lua/modules/plugins/completion.lua
- lua/modules/plugins/editor.lua
- lua/modules/plugins/tool.lua
- lua/modules/plugins/ui.lua
This fixes #866 and closes #867.
cc @fecet
> perf!: consolidated updates to address performance issues

- lua/modules/plugins/editor.lua
cc @Jint-lzxy 
A redemption PR :sob:
> perf(pack): update `nvim-bufdel` lazy-loading events.

- lua/core/settings.lua
- lua/modules/plugins/completion.lua
This PR fixed all problematic calls regarding `lsp_signature`. See https://github.com/ayamir/nvimdots/pull/840#issuecomment-1646737012.
> perf(lsp_signature): fix input delay

- lua/core/options.lua
- lua/core/settings.lua
> fix(provider): leave provider specifications to user

- .github/workflows/lint_code.yml
- lua/keymap/tool.lua
- lua/modules/configs/editor/rainbow_delims.lua
- lua/modules/configs/tool/dap/clients/codelldb.lua
- lua/modules/configs/tool/dap/clients/delve.lua
- lua/modules/configs/tool/dap/clients/lldb.lua
- lua/modules/configs/tool/dap/clients/python.lua
- lua/modules/configs/tool/dap/dap-keymap.lua
- lua/modules/configs/tool/dap/dapui.lua
- lua/modules/configs/tool/dap/init.lua
- lua/modules/utils/dap.lua
Recent updates to `nvim-dap` made integrated terminals possibe right inside Neovim. This PR implemented basic support for this feature, but it's still necessary to adjust the settings of each debugger to correctly redirect stdio to the specified terminal (inside Neovim). More info: [dap-terminal](https://github.com/mfussenegger/nvim-dap/blob/d17d1bba23ec72a157bd183c57840c39e323f515/doc/dap.txt#L549-L602).
I'm not that familiar with other debuggers so I only adjusted the settings for `codelldb` (AFAIK `lldb-vscode` has zero support for IO redirection). Someone who understands these _other_ debuggers could help make several changes before merging :) Any help will be appreciated!
Aditionally, `K` (responsible for `require('dapui').eval()`) will be set as a buffer-local keymap (mode: `n|v`) …
> feat(dap)!: support integrated terminals (io in neovim)

- .github/workflows/lint_code.yml
- lua/core/event.lua
- lua/modules/configs/tool/dap/dap-keymap.lua
I'll document/explain these changes later today. It's a bit late ;)
Ref: #899
Resolves #899
> fix(dap-keymap): properly create and destroy keymaps

- .github/workflows/lint_code.yml
- lua/core/event.lua
- lua/modules/configs/tool/dap/dap-keymap.lua
- lua/modules/configs/tool/dap/init.lua
- lua/modules/utils/keymap.lua
IMO the cognitive complexity of changes introduced by #902 is too high. This PR makes `dap-keymap.lua` do whatever it should have done - delete old keymaps and restore them when appropriate.
> fix(dap-keymap): simplify keymap implementation

- lua/modules/configs/editor/autoclose.lua
1. disable autoclose `''` for **rust** because `'` is the symbol for lifetimes.
2. disable autoclose `<>` for **cpp only** because `<<` and `>>` are operators in cpp but `<>` is often used as generic type.
> fix: only disable autoclose for specific filetypes

- lua/modules/configs/tool/toggleterm.lua
IMO this is a good patch (taken from #913) and should be merged.
> fix(toggleterm): `start_in_insert` not working

- lua/modules/configs/editor/rainbow_delims.lua
After some experiments, it seems `rainbow_delims`'s local strategy will inevitably have a large performance hit while handling any excessively tall ASTs. This PR restricts this behavior where appropriate.
> fix(rainbow_delims): specify thresholds for all fts

- lua/core/settings.lua
- lua/modules/configs/completion/cmp.lua
- lua/modules/plugins/completion.lua
Not all users use copilot and not all situations we need it. So I add a switch to it. (Sorry for the wrong branch name)
> feat: add setting for copilot enable or not.

- lua/modules/configs/completion/lspsaga.lua
IMO It's pretty counterintuitive to have cursor placed on the target identifier before toggling code action(s). This PR changes the behavior.
Ref: https://github.com/nvimdev/lspsaga.nvim/commit/a11b436aea63e305f9a94432e89bb26609d7a56c
> feat(lspsaga): make codeaction effective linewise

- scripts/install.ps1
- scripts/install.sh
This commit considers the following extreme cases:
* `lua/user` cannot be opened or modified.
* **Solution:** Force overwrite w/ `-Force` or `-f`
* Recent macOS distributions shipped an implementation that is incompatible with **both** BSD and GNU `cp`.
* **Solution:** Make it compatible (`-RpP`)
```console
-P    No symbolic links are followed.  This is the default if the -R option is specified.
-R    If source_file designates a directory, cp copies the directory and the entire subtree connected at that point.  If the source_file ends in a /, the contents of the directory are copied rather than the directory itself.
This option also causes symbolic links to be copied, rather than indirected through, and for cp to create special files rather than copying them as normal files.  Created …
```
> fix(scripts): consider extreme cases

- lua/core/settings.lua
- Enable `gofumpt` in `gopls` setting since it's widely used in Go community
- Import missing packages via `goimports` on save.
> feat(null_ls_deps): add `gofumpt` and `gopls`

- lua/modules/plugins/ui.lua
Neodim's recent updates (specifically https://github.com/zbirenbaum/neodim/commit/2ac2f25d221bf34f70b79d0ab1d313e9826859c3) introduced/utilized some of `nvim 0.10`'s APIs, which might be a source of trouble for nvim 0.9.\*, so IMO we'd better pin `neodim` to v2.0 to avoid potential issues :D
> fix(neodim): pin to v2.0

- nixos/neovim/default.nix
Go-related lang support was added in #996.
When launching neovim on NixOS, building these tools fails due to missing `go`.
Therefore, add `go` to `programs.neovim.extraPackages`.
> fix(nixos): Add go lang.

- lua/core/options.lua
- lua/modules/plugins/tool.lua
- nixos/neovim/default.nix
- scripts/install.ps1
- tutor/dots.tutor
https://github.com/nvim-telescope/telescope-frecency.nvim?tab=readme-ov-file#remove-dependency-for-sqlitelua
WIP
might to trigger `:FrecencyMigrateDB` and `:FrecencyValidate` to some ppl.
> refactor(telescope-frecency)!: remove support for `sqlite.lua`

- lua/core/settings.lua
- lua/modules/configs/completion/formatting.lua
- lua/modules/plugins/completion.lua
Propose it because this requirement is common as the readme of this plugin: https://github.com/joechrisellis/lsp-format-modifications.nvim#what-problem-does-this-solve
Additionally, it's inevitable to add this function by modifying the `formatting.lua` file, which isn't what we want to see.
> feat: support formatting changed lines only

- lua/core/init.lua
- lua/core/settings.lua
This PR did two things.
+ Separate the config of `guifont` and `neovide`.
+ Add two settings entrys in `lua/core/settings.lua` named as `gui_config` and `neovide_config`.
This PR is backward-compatible.
> feat: customized `neovide` and `gui` config

- lua/modules/configs/ui/lualine.lua
By utilizing "auto" theme as mentioned [here](https://github.com/nvim-lualine/lualine.nvim/blob/master/THEMES.md#auto), this PR corrects the appearance of `lualine` when using other colorschemes.
Of course, users using `catppuccin` won't be influenced.
> fix(lualine): automatically load theme for the active colorscheme

- lua/modules/configs/completion/null-ls.lua
This PR supports applying formatter args set in `user/configs/formatters`. The related wiki will be updated after merging.
> fix: auto apply formatter args set in `user/configs/formatters`.

- lua/core/init.lua
since the numeric keys are ignored as whole in `iparis` iteration, configurations in `neovide_config` actually aren't set to neovide, after switching `ipairs` to `pairs`, configurations are set properly.
> fix(neovide): neovide is not set up correctly because of `ipairs`

- lua/modules/configs/editor/treesitter.lua
https://github.com/nvim-treesitter/nvim-treesitter/commit/f53e6e82df8efb17b9b04d2f6d5ad64755786b7e fixed the last dangling syntax issue in C/C++, So IMO we can now completely switch to treesitter-based highlight (and indent) lol
> feat(treesitter): use ts-indent and disable legacy syntax engine

- lua/keymap/tool.lua
When I use <leader>fc to switch colorschemes,I can't see the change in real time.
So I made some changes
> feat(telescope): support live preview of currently selected colorscheme

- lua/modules/configs/lang/bqf.lua
- lua/modules/plugins/lang.lua
IMO we could think about bringing `nvim-bqf` back. Not only does it make nvim's quickfix mode a breeze to use, but it also sidesteps some of the issues we had before, like #981. Plus, it's a plugin that loads on demand, so it shouldn't cause any side effects 😄
> feat(plugins): add `nvim-bqf`

- scripts/install.ps1
IMO the default choice for dependency installation in `install.ps1` is a bit misleading (see Discussion #1106). afaik most users won't even "visit" the dynamic provider feature of Neovim, and those who know what they're doing can still continue with the dependency installation by typing `Y/y`. So I think a more reasonable default should be `N` (i.e. skipping provider installation altogether.)
> feat(script): skip dependency installation by default

- lua/modules/configs/completion/cmp.lua
https://github.com/ayamir/nvimdots/discussions/1116
> fix(cmp): don't auto select the first completion candidate

- lua/modules/configs/ui/bufferline.lua
When I use the close button on bufferline, it often exits abnormally.
After using BufDel %d instead of bdelete! %d, this situation no longer occurs.
> fix(bufferline): use `BufDel %d` instead of `bdelete! %d`

- lua/modules/configs/ui/bufferline.lua
This is a follow-up fix for #1136. It prevents `bufferline` from tripping over errors thrown by `nvim-bufdel`, and is also keeping up with the upstream close command (`bdelete!`)
> fix(bufferline): avoid unnecessary user interaction

- lua/modules/configs/completion/mason-lspconfig.lua
- lua/modules/configs/lang/rust.lua
This PR does three things:
- Allows users to overwrite the init options of `rustaceanvim` thru their custom configs;
- It gives a heads-up to users that if they're still manually setting up `rust_analyzer`, [this will result in two identical servers being spawned](https://github.com/ayamir/nvimdots/pull/1140#issuecomment-1881190708);
- DAP-related settings are disabled by default to avoid potential conflicts with previous user configurations. IMO since we already have [configs for `codelldb`](https://github.com/ayamir/nvimdots/blob/f2cf03b254c21a69d3654c2c05014cd411ac14e2/lua/modules/configs/tool/dap/clients/codelldb.lua#L46) that can be used, users can simply tweak those configs on their own. But I'm not 2 sure about this, as I personally don't do much rust development. What do u guys …
> fix(rust): respect user configs

- lua/core/event.lua
see
https://github.com/LazyVim/LazyVim/commit/02bc41412a14c1c0bb823421ef82ff5596f42571
https://github.com/nvim-telescope/telescope.nvim/issues/699
https://github.com/nvim-telescope/telescope.nvim/pull/2726
> fix(telescope): remove telescope folding hack since PR with fix has been merged upstream

- lua/keymap/helpers.lua
- lua/modules/configs/ui/catppuccin.lua
- lua/modules/configs/ui/notify.lua
- lua/modules/utils/init.lua
This should fix #1120.
cc @vabatta It would be awesome if u could review this PR lol
> fix(utils): respect `o:background`

- lua/modules/configs/ui/scrollview.lua
https://github.com/dstein64/nvim-scrollview?tab=readme-ov-file#lua-example
A Lua `setup()` function is provided for convenience, to set globally scoped options (the 'scrollview_' prefix is omitted).
> fix(scrollview): omit the `scrollview_` prefix

- lua/keymap/helpers.lua
- lua/keymap/tool.lua
> feat: search with selection text.

- lua/modules/configs/completion/formatting.lua
1. adapt neovim new api to lsp clients. 
2. suppress the useless diagnostic warnings.
3. introduce `method` variable for `"textDocument/formatting"`.
> fix: eliminate warning in formatting.lua.

- lua/modules/plugins/completion.lua
> feat!: pin `none-ls` until upstream deprecation is finished

- lua/core/options.lua
- lua/modules/configs/ui/lualine.lua
Global statusline is more friendly for multiple window splits.
Besides, I disabled all extension which looks not suitable for global statusline.
> feat(ui): enable global statusline, disable all extension.

- .github/workflows/lint_code.yml
- README.md
- lua/keymap/helpers.lua
- lua/keymap/tool.lua
- lua/modules/configs/completion/cmp.lua
- lua/modules/configs/tool/dap/clients/python.lua
- lua/modules/configs/tool/telescope.lua
- scripts/install.ps1
- scripts/install.sh
- tutor/dots.tutor
This commit mainly tackled several minor touch-ups and syntax improvements:
- Addressed `luacheck` issues from previous commits.
- Added some to-do comments for `_buf_vtext`.
- Eliminated redundant/outdated options.
- Temporarily removed the ability to install nightly-version configs and updated the names of relevant functions: - `clone_by_https_or_ssh` -> `clone_repo`
- Rewrote `dotstutor` to make it more readable.
> chore: cleanup and minor syntax improvements

- lua/modules/configs/completion/cmp.lua
using that, buffer completion include all buffer, not only one buffer.
https://github.com/hrsh7th/cmp-buffer
get_bufnrs (type: fun(): number[])
Default: function() return { vim.api.nvim_get_current_buf() } end
A function that specifies the buffer numbers to complete.
> feat(cmp): more completion candidates from opened buffers.

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/custom_config.yml
- .github/ISSUE_TEMPLATE/lsp_issue_report.yml
- README.md
> docs: mention the experimental nature of the 0.10 branch

- lua/modules/configs/ui/todo.lua
there are some minor issue w/ current `todo-comment.nvim`'s config:
In `colors`, we define it as following
```lua
colors = {
error = { "DiagnosticError", "ErrorMsg", "#DC2626" },
warning = { "DiagnosticWarn", "WarningMsg", "#ff8800" },
info = { "DiagnosticInfo", "#2563EB" },
hint = { "DiagnosticHint", "#F5C2E7" },
default = { "Conditional", "#7C3AED" },
test = { "Identifier", "#4FC1FF" },
},
```
However, it's over written to these colors:
In `:Inspect`
Should we just remove the `colors` section or enforce colors as such:
```lua
local error_red = "#F44747"
local warning_orange = "#ff8800"
local info_yellow = "#FFCC66"
local hint_blue = "#4FC1FF"
local perf_purple = "#7C3AED"
local note_green = "#10B981"
require("modules.utils").load_plugin("todo-comments", {
signs = true, -- show icons in …
```
> fix(todo-comment): add missing keywords

- lua/core/event.lua
After the commit [`f1dfe32`](https://github.com/neovim/neovim/commit/f1dfe32bf5552197e0068298b0527526a4f918b1) in `neovim`, the function `vim.lsp.inlay_hint.enable(buffer_number, enable)` was changed to `vim.lsp.inlay_hint.enable(enable: boolean, filter: table)`, where the original approach would lead to an error.
**I suspect there could be further changes to this API.**
> fix: inlay_hint error

- lua/modules/configs/ui/lualine.lua
I know the commit message might be a bit difficult to grasp, but I'm struggling to find a clearer way to describe it :( Essentially, this commit ensures that when our custom separator is used, default separators (as defined by `section_separators` and `component_separators`) are not added to the statusline. This prevents certain extreme scenarios where the default separator cannot be concealed, such as when in terminal mode with `:ToggleTerm direction=horizontal`.
> fix(lualine): disable default separators for custom separator

- lua/modules/configs/tool/toggleterm.lua
IMO this is more reasonable behavior when nvim-tree opened as some users discussed in https://github.com/akinsho/toggleterm.nvim/issues/97
> fix: prevent horizontal terminal from obscuring `nvim-tree`

- lua/modules/configs/tool/nvim-tree.lua
This PR disable `<C-e>` in `nvim-tree` buffer which will open file in place originally. IMO just leaving it to scroll is better and we usually don't want to open a file in such a narrow buffer.
> pref: disable `<C-e>` for open-in-place inside nvim-tree

- lua/modules/configs/ui/catppuccin.lua
Based on the [upstream spec](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#types), `@property` is typically associated with the "key" in key/value pairs. So IMO since we don't give special treatment to the "values" (such as assigning them an "italic" property), we should treat the "keys" in the same manner as well.
> feat(catppuccin): remove all styles of `@property`

- lua/modules/plugins/lang.lua
rustaceanvim does work on my computer and ^4 is recommended on rustaceanvim README.md
> fix: set rustaceanvim version to ^4

- lua/core/init.lua
use `""` instead of `nil` to fix auto-exit when calling `toggleterm` on Windows.
> fix toggleterm auto-exit on Windows

- lua/modules/configs/editor/ts-context.lua
default zindex of glance [dnlhc/glance.nvim] floatterm is 45. It can display on glance.
> fix: utilize `ts-context` in `glance` preview window

- lua/keymap/tool.lua
- lua/modules/configs/tool/trouble.lua
- lua/modules/configs/ui/catppuccin.lua
This PR includes the following changes:
- **REMOVED** all features unrelated to the original purpose of `trouble.nvim`, such as LSP References ([Glance](https://github.com/DNLHC/glance.nvim) covers this) and qf-list preview ([bqf](https://github.com/kevinhwang91/nvim-bqf) handles this).
- Added a custom mapping for searching project diagnostics. This is slightly different from workspace diagnostics: one is defined by the language server itself (e.g., see [LuaLS's documentation on workspace diagnostics](https://github.com/LuaLS/lua-language-server/wiki/Libraries)), while the other is determined with assistance from `project.nvim`.
- General cleanup: I deliberately excluded `trouble.nvim`'s LspKind support (e.g., LSP definitions, references, implementations, type definitions, etc.) from our …
> feat(trouble)!: v3 support

- lua/modules/configs/ui/alpha.lua
> fix(alpha): cannot cast `string` to `integer` for winheight

- lua/modules/plugins/completion.lua
As per `:h luasnip-lsp-snippets-transformations`
> feat(luasnip): support ECMAScript regexes

- .github/workflows/update_flake.yml
- .gitignore
- flake.nix
This commit introduced three changes:
1. Opt for a shallow clone whenever we run the `update_flake` workflow since there's no need to retrive past commits.
2. Deleted `result` from `.gitignore` bc I couldn't track down its source (correct me if I'm wrong!)
3. Ensure either XCode or the CLT is installed on macOS before running `otool`. These aren't included by default on a fresh macOS install, and using `xcrun` can sort out those dependency snags.
btw @CharlesChiuGit @misumisumi do u think it's worth considering enforcing library policies for the pre-built binaries that Mason uses on macOS, similar to our approach on NixOS? This enforcement could involve setting `DYLD_*_LIBRARY_PATH` or utilizing `install_name_tool` (see manual below). One potential concern I see with this change is that …
> chore(nix): cleanup

- lua/core/global.lua
All of these "workarounds" should no longer be necessary since Neovim v0.6 or so.
---
> chore(global): cleanup legacy code

- lua/core/init.lua
- lua/core/options.lua
This is to mitigate a regression introduced by #1296, where a leading path separator is needed to properly delineate the path returned by `stdpath()`.
---
> fix(core): missing leading path separator

- nixos/neovim/default.nix
https://github.com/ayamir/nvimdots/pull/1260#issuecomment-2191929399
`lazy-lock.json` managed by `nix/store` is symbolically linked to `${XDG_CONFIG_DIR}/nvim/lazy-lock.json`, but since it is read-only, there is a problem that it has low affinity with lazy.nvim.
Therefore, lazy-lock.json is managed locally, and when lazy-lock.json in the repository is updated, it is merged to achieve both reproducibility and convenience.
It will be updated with the workflow shown below when home-manager activation.
1. `lazy-lock.json` in the repository is managed as `lazy-lock.fixed.json` in `/nix/store`.
2. When created symlink to `${XDG_CONFIG_DIR}/nvim`, one of the following will be executed.
1. Not existing `lazy-lock.json` under `${XDG_CONFIG_DIR}/nvim`, copy to then.
2. Existing `lazy-lock.json` …
> feat(nixos): add mergeLazyLock option

- lua/modules/configs/completion/cmp.lua
- lua/modules/configs/completion/mason-lspconfig.lua
1. https://github.com/hrsh7th/cmp-nvim-lsp/issues/38
2. some times first candidates can't be selected with our current cmp keymaps, ~~still trying to pin-point what's the cause.~~
How to reproduce 2.
1. Open ramdon lua file
2. Type `local fu` (or other keywords that can trigger snippets) and wait for the cmp windows to pop.
3. Press `<Tab>` to select the first cmp item.
It will keep flashing but won't select any cmp item. However, it can somehow use `<Up>` and `<Down>` to select the cmp item.
This error doesn't limited to `cmp-nvim-lsp`, sometimes `luasnip` has this issue too. 
I think this issue is mostly related to snippets.
https://github.com/ayamir/nvimdots/assets/32497323/3c6b4bb8-3e16-4595-a571-265ae1d40723
> fix: cmp snippets source selecting issue

- LICENSE
- README.md
This PR proposes changing our config's license to the BSD 3-clause license. It also updates the README to acknowledge [aarnphm](https://github.com/aarnphm) and [misumisumi](https://github.com/misumisumi) as main contributors. I chose the BSD 3-clause license primarily because it includes a non-endorsement clause and does not permit [sublicensing](https://softwareengineering.stackexchange.com/a/189647) (which the MIT license lacks afaiu).
> feat: credit all collaborators as copyright holders

- lua/modules/configs/tool/which-key.lua
This is a follow-up fix for which-key's v3 rewrite. It simply restores the behaviors to match v2's default, so there shouldn't be any explicit changes.
(Now the user can use which-key in visual/selection mode without the annoying box that distracts attention, which is superb 🥳)
> fix(which-key): config option `modes` has been deprecated

- lua/keymap/lang.lua
- lua/modules/configs/lang/render-markdown.lua
- lua/modules/configs/ui/catppuccin.lua
- lua/modules/plugins/lang.lua
https://github.com/MeanderingProgrammer/render-markdown.nvim
> feat: add `render-markdown.nvim` for md workflow

- lua/core/init.lua
- lua/core/pack.lua
> fix(core): disable rtp plugins via `lazy.nvim`, #1339

- lua/core/init.lua
- lua/core/options.lua
- lua/core/pack.lua
This commit addresses a few regressions introduced by #1340:
* The `tutor` plugin was accidentally disabled.
* netrw, along with its configuration, was mistakenly disabled.
* EditorConfig is now being implicitly disabled, which wasn't intended before #1340.
> fix: some vim plugins get disabled by mistake

- lua/modules/configs/completion/null-ls.lua
This commit disables `clang_format` for all Java files. The main reason is to ensure that formatting is managed by `jdtls`, which adheres to a widely accepted standard. Given that Java developers have a strong preference for this approach, it makes more sense to let a Java-specific language server handle the formatting rather than relying on a more general-purpose formatter like `clang_format`.
> feat(clang_format): disable formatting for all Java files

- lua/modules/configs/tool/dropbar.lua
The `icons.kinds.use_devicons` option has been deprecated. This commit simply removes it, as the detection of the appropriate devicon is now managed automatically within the relevant callbacks.
Upstream commit: https://github.com/Bekaboo/dropbar.nvim/commit/a1b893ccc96080f0d167eef6e9310a40ef85ccba
> fix(dropbar): remove deprecated `icons.kinds.use_devicons`

- lua/modules/utils/init.lua
This commit want to avoid the case when `get_palette()` call happens before `vim.g.colors_name` be initialized, which will raise error.
> fix: check if `vim.g.colors_name` is nil.

- lua/modules/utils/init.lua
Due to the change in a631be214b3b537d7b5d7c999e21ba59a3a467fc, an error will now occur if a color scheme other than catppuccin is used.
Previously, when using another color scheme, it seemed to fall back to the defined palette.
This change supports retrieval of user-defined color palettes, allowing you to use a wider range of color schemes.
- error message
> fix: supports getting of user-defined color palettes

- lua/modules/configs/completion/formatting.lua
- lua/modules/configs/ui/lualine.lua
doc [here](https://neovim.io/doc/user/lsp.html#vim.lsp.get_clients())
> fix: client filter argument typo

- lua/modules/configs/completion/mason-lspconfig.lua
https://github.com/ayamir/nvimdots/discussions/1375
> fix: merge user customized config with predefined.

- lua/modules/utils/init.lua
This commit should fix a weird bug where `nvim_get_hl` would return an empty dict when trying to get `hl-Statusline` inside `toggleterm`. Not 100% sure why this was happening or what exact conditions caused it, but with this fix lualine now shows the right backgrounds in terminal mode!
- **Before (notice that eg the git section doesn't have proper `guibg`):**
- **After:**
> fix(utils): hl-Statusline retrieval issue in toggleterm

- lua/modules/plugins/ui.lua
Currently we set `bufferline.nvim` loaded when `BufReadPost`, it will cause the bufferline doesn't appear when we open file by telescope or nvim-tree. This patch make it load when `BufReadPre`.
> fix: avoid bufferline not appear when open file by telescope or nvim-tree.

- lua/modules/configs/completion/luasnip.lua
This patch lazy loads user's customized snippets from `lua/user/snips`.
The usage is copy `lua/snips` to `lua/user/snips/` first and create your snippets like the existing examples, i.e.:
```shell
cd ~/.config/nvim
mkdir -p ./lua/user/snips/
cp -vr ./snips/* ./lua/user/snips/
cd ./lua/user/snips/snippets/
rm -rf *
```
Add your customized snippets for `go.json` like this:
```shell
touch go.json
nvim go.json
```
```json
{
"if err": {
"prefix": "ie",
"body": "if err != nil {\n\t$1\n}\n$2",
"description": "Snippet for if err"
}
}
```
Then you can use it:
Close #1385 @greggh
> feat: support user customized snippets.

- lua/keymap/tool.lua
This patch fix the bug that searching selection region doesn't works as expect. Current main branch will search word under cursor rather than selection region.
> fix: search selection pattern under visual mode.

- lua/modules/configs/tool/search.lua
This patch add `--no-ignore` arg for telescope builtin find_files when cwd is nvim config dir. 
@Gregg
> fix: search user config when cwd is nvim config path.

- lua/keymap/editor.lua
- lua/keymap/ui.lua
This is basically a follow-up for #1363! I combined builtin & plugin keymaps, cleaned up some comments (lol "suckless"), and made `ui.lua` export-ready
> feat(keymap): improve structure and documentations

- lua/modules/utils/init.lua
This commit is a follow-up fix for #1369 (and potentially #1371), simplifying the change to a single line:
```diff
--- /dev/fd/14	2025-01-18 15:44:55
+++ /dev/fd/15	2025-01-18 15:44:55
@@ -1 +1 @@
-palette = vim.g.colors_name:find("catppuccin") and require("catppuccin.palettes").get_palette()
+palette = (vim.g.colors_name or ""):find("catppuccin") and require("catppuccin.palettes").get_palette()
```
> fix(utils): add nil check for `g:colors_name`

- lua/modules/configs/completion/mason-lspconfig.lua
This commit is a follow-up fix for #1376 to delay merging user & default configs as much as we can to avoid extra overhead.
> fix(lsp): only merge configs when absolutely needed

- lua/keymap/completion.lua
- lua/keymap/editor.lua
- lua/keymap/ui.lua
a break feature lewis6991/gitsigns.nvim@8b74e560f7cba19b45b7d72a3cf8fb769316d259 upstream.
Keymap `select_hunk`  is a fix according to [keymaps in readme](https://github.com/lewis6991/gitsigns.nvim/blob/main/README.md#keymaps). I tested in my PC and It only works on selecting `vih`,  not supports  `dih` and `yih`, though I think it's enough for use.
`toggle display` keymaps is moved due to https://github.com/ayamir/nvimdots/pull/1397#issuecomment-2603741689
> fix(keymaps): update `toggle display` and `gitsigns` keymaps

- lua/modules/configs/ui/edgy.lua
- lua/modules/plugins/ui.lua
This commit basically does some cleanup to #1393:
1. Replaced fixed width/height values w relative dimensions.
2. Removed unnecessary keymaps that were not linked to any other config components, allowing users more flexibility to customize their key mappings.
> chore(edgy): cleanup

- lua/keymap/ui.lua
This commit is a follow-up fix for #1405:
- `stage_hunk` now toggles between staging and unstaging a hunk (keymap description updated)
- Changed the callback for `text_object` to `select_hunk`:
```
> git log --grep text_object
commit e22e37897ac328d3f7e00e354852b6c9ffdd1e5d
Author: Lewis Russell <lewis6991@gmail.com>
Date:   Thu Mar 25 14:47:33 2021 +0000
Rename text_object() -> select_hunk()
```
> fix(gitsigns.keymap): update functions and descriptions

- .github/workflows/lint_code.yml
- lua/keymap/completion.lua
- lua/keymap/helpers.lua
- lua/keymap/lang.lua
This commit removed some legacy configs (not sure where they came from...? correct me if I'm wrong!). Also renamed `_toggle_diagnostics` -> `_toggle_virtualtext` for clearer intent.
> chore(keymap): clean up legacy configs & rename toggle function

- lua/modules/configs/editor/matchup.lua
- lua/modules/plugins/editor.lua
This commit turned on a few vim-matchup features that pair nicely with treesitter imo.
> chore(matchup): enable some vim-matchup features

- lua/modules/configs/completion/mason.lua
The luv doc says the `on_stderr` callback is also called whenever the program exits, not just when smth is written to stderr. So we should only notify if there's a real error in `msg_stream`.
> fix(mason): add nil check to on_stderr callback in install-pylsp-plugins

- lua/modules/configs/tool/dropbar.lua
This commit replaces the default `path` source with a custom one to prevent the path section from always displaying (dropbar would incorrectly display the full path when switching eg to a terminal window as it would assume the terminal's cwd as the current working directory)
> feat(dropbar): replace `path` with custom source

- lua/modules/configs/ui/edgy.lua
- lua/modules/utils/init.lua
This reverts commit 7056741dd38901ff5b615ed2b604e088691255b5.
Sorry for the noise but I'm a lil confused about this new option...? Like idk if the performance difference between these two is even that big, and maybe it's not actually working as expected?
> Revert "fix: support overwrite when merge config. (#1394)"

- lua/modules/configs/ui/lualine.lua
- lua/modules/utils/init.lua
This commit addresses the root cause of #1381 by allowing lualine to automatically select the default background color. Previously, lualine attempted to retrieve the background manually, which could lead to issues when querying in a different namespace (and resulting in an empty dictionary).
> fix(lualine): resolve background color defaulting issue

- lua/keymap/completion.lua
This commit prevents lag when using `gr` by avoiding conflicts with new keymaps Neovim defines with this prefix.
> fix(keymap): prevent new builtins from interfering with our keymap

- lua/keymap/helpers.lua
Previous impl won't work when toggle for the first time.
> fix: toggle inlay hints correctly.

- lua/core/settings.lua
- lua/keymap/helpers.lua
- lua/modules/configs/completion/mason-lspconfig.lua
- lua/modules/configs/completion/tiny-inline-diagnostic.lua
- lua/modules/plugins/completion.lua
This PR remove the setting entry for virtual text b/c [tiny-inline-diagnostic.nvim](https://github.com/rachartier/tiny-inline-diagnostic.nvim) will manage it.
Effect:
Only show diagnostic message at current cursor position to avoid too many messages disrupt attention. We have `Trouble` and `g[`/`g]` to navigate between multiple diagnostic messages, so this is acceptable for me.
> feat: use tiny inline diagnostics to manage virtual text.

- lua/modules/configs/completion/mason-lspconfig.lua
- lua/modules/plugins/completion.lua
- fix ayamir/nvimdots#1461
Having reviewed the [release note](https://github.com/mason-org/mason-lspconfig.nvim/releases/tag/v2.0.0), it appears we can support the new API without significant changes to the existing code. 
This provides a base for considering v2 support.
Currently, we provide our own handlers, but we could leverage [Neovim's](https://neovim.io/doc/user/lsp.html) [built-in mechanism](https://neovim.io/doc/user/options.html#after-directory) for this.
Specifically, we can create a file at `after/lsp/<lsp-name>.lua` within the project root. In my local environment, this allowed me to override the LSP settings.
However, this approach might make it more difficult to separate user configurations from the repository's defaults.
> refactor(mason): support for mason and mason-lspconfig v2

- lua/core/settings.lua
- lua/keymap/completion.lua
- lua/keymap/tool.lua
- lua/modules/configs/tool/fzf-lua.lua
- lua/modules/configs/tool/search.lua
- lua/modules/configs/tool/telescope.lua
- lua/modules/plugins/tool.lua
This pr introduce `fzf-lua` as fuzzy searcher to replace part functionalies of `telescope.nvim` to achieve higher performance when search in a big repo. I forked and rewrote `search.nvim` to make it support `fzf-lua`. Not all pickers are equivalent such as frecency and not all pickers are replaced, but now it basically works. It will close #1463.
https://github.com/user-attachments/assets/abb2d597-b856-4085-a516-7c893609961e
@Elite-zx You can try it now.
> refactor: introduce fzf-lua as an alternative of telescope.

- lua/modules/plugins/editor.lua
This PR adds `submodule=false` in `rainbow-delimiters.nvim` installation config.
Sometimes I encountered an error while updating `rainbow-delimiters.nvim`. The error indicated that some submodules are not found. So I check the plugin, the [README](https://github.com/HiPhish/rainbow-delimiters.nvim?tab=readme-ov-file#installation) says:
> you do not need the Git submodules of this repository. They are just used for development and won't cause any harm, they will just bloat your setup.
And I found the `bin` submodule in the [test directory](https://github.com/HiPhish/rainbow-delimiters.nvim/tree/master/test) cannot be reached, which might be a cause. Although I'm not sure if the updating error always happens, it's safe to remove these submodules.
> fix: install rainbow-delimiters.nvim without cloning submodules.

- README.md
This commit add discord and deepwiki for nvimdots. The badge style is changed to normal for compatible with new added deepwiki badge.
> feat: add discord and deepwiki, change badge style.

- lua/modules/configs/tool/dap/clients/delve.lua
- lua/modules/configs/tool/dap/clients/python.lua
https://github.com/mason-org/mason.nvim/blob/7c7318e8bae7e3536ef6b9e86b9e38e74f2e125e/CHANGELOG.md?plain=1#L65
> fix(dap): deprecate `Package:get_install_path()`

- .github/workflows/lint_code.yml
- lua/core/settings.lua
- lua/keymap/completion.lua
- lua/keymap/helpers.lua
- lua/modules/configs/completion/mason-lspconfig.lua
- lua/modules/configs/completion/tiny-inline-diagnostic.lua
- lua/modules/plugins/completion.lua
This change is mostly abt cleaning up how we handle inline diagnostics everywhere in the repo! The main visible difference i think ppl will notice is that i switched tiny-inline-diagnostic's preset from "modern" to "simple" cuz it seems to fit better w what we had before (but always open to switching it back lol). Aside from that, i went thru and renamed all the mentions of "virtual text" to "virtual lines" to be more accurate. Also i changed the plugin to load right at startup cuz i just took a look at its code and it acc changes some of nvim's default diagnostic settings and pretends those are the defaults, so it really needs to start early so nothing else overwrites its changes ~~(lsp shenanigans lol)~~. That said, it's still pretty lazy under the hood, so it shouldn't slow down …
> refactor(lsp): consistently use tiny-inline-diagnostic API

- lua/modules/configs/completion/lsp.lua
- lua/modules/configs/completion/mason-lspconfig.lua
- lua/modules/configs/editor/persisted.lua
- lua/modules/plugins/completion.lua
This PR should acc fix #1472 and #1479 cuz iirc the root cause was that lspconfig changed how `LspStart` works. Now it only starts one _specific_ server (passed via the first argument), instead of starting all matching servers automatically. So we gotta manually start all the servers that match the current filetype instead.
> fix: LSP start logic

- lua/core/global.lua
This pr use realpath to replace vim related path to avoid `--no-ignore` failure b/c we use `vim_path` to compare with `vim.uv.cwd`.
> fix: use realpath of vim related path

- lua/core/global.lua
This pr will fix #1521. In fact, only `vim_path` is needed to be a realpath.
> fix: only use realpath for vim_path
